/*
FILE : downloadFile.cpp
PROJECT : Omni360
PROGRAMMER : 951261
DESCRIPTION : Downloads a file. If the file is larger than 4GB, it splits it into multiple parts.
*/

/**
 * ----------------------------------------------------------------------------
 * XboxTLS Example Client
 * ----------------------------------------------------------------------------
 * This is a minimal demonstration of the XboxTLS library running on a
 * modded Xbox 360. It showcases how to perform a secure TLS 1.2 connection
 * to a remote server using the BearSSL cryptographic library (embedded into
 * the XboxTLS implementation).
 *
 * ----------------------------------------------------------------------------
 * Features:
 * - Initializes the Xbox 360 network stack (XNet, Winsock).
 * - Resolves a domain name using Xbox 360's DNS (XNetDnsLookup).
 * - Supports TLS 1.2 with both RSA and Elliptic Curve (EC) trust anchors.
 * - Performs a secure TLS handshake and sends an HTTPS GET(POST also supported) request.
 * - Prints the received HTTP response using XboxTLS_Read and debug output.
 *
 * ----------------------------------------------------------------------------
 * Library Dependencies:
 * - XboxTLS (this project's core TLS wrapper).
 * - BearSSL (used internally for TLS 1.2, x.509, ECDSA/RSA, HMAC, etc.).
 *
 * ----------------------------------------------------------------------------
 * Trust Anchor Notes:
 * This client supports two types of root certificate trust anchors:
 *   1. EC (Elliptic Curve) trust anchors - commonly used with modern CAs.
 *   2. RSA trust anchors - still widely used for backwards compatibility.
 *
 * Trust anchors come from TrustAnchors.h, generated from real root
 * certificates by tools/make_trust_anchors.py - see addTrustAnchors.
 *
 * ----------------------------------------------------------------------------
 * Usage Notes:
 * - This client is designed for development/testing on modded Xbox 360 units.
 * - Built using the Xbox 360 XDK with support for WinSock and XNet.
 * - This implementation assumes you are targeting TLS 1.2 endpoints.
 *   It does not support TLS 1.3.
 *
 * ----------------------------------------------------------------------------
 * Author: Jakob Rangel
 * License: MIT / Open Source
 */
#include <iostream>

#include "downloadFile.h"
#include "HttpResponse.h" // for HttpsSession's reads
#include "XboxTLS.h"
#include "dns.h"
#include "parsing.h"
#include "OutputConsole.h"

#include <xtl.h>
#include "TrustAnchors.h" // generated by tools/make_trust_anchors.py
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <errno.h>
#include <vector>

#define ERROR(s) (log_printf("\nERROR: %s\n", s))
#define DEBUG_PRINT(s) (log_printf(s));

unsigned long long outputBufferPointer = 0;

// Yeah yeah, I know I already have this in 7z decompression
bool FormatBytes(
    unsigned long long bytes,
    char *output,
    size_t outputSize)
{
    if (!output || outputSize == 0)
        return false;

    static const char *units[] =
    {
        "B", "KB", "MB", "GB", "TB"
    };

    double value = (double)bytes;
    unsigned int unitIndex = 0;

    while (value >= 1024.0 && unitIndex < 4)
    {
        value /= 1024.0;
        ++unitIndex;
    }

    int result;

    if (unitIndex == 0)
    {
        result = _snprintf(
            output,
            outputSize,
            "%I64u B",
            bytes);
    }
    else if (value >= 100.0)
    {
        result = _snprintf(
            output,
            outputSize,
            "%.0f %s",
            value,
            units[unitIndex]);
    }
    else if (value >= 10.0)
    {
        result = _snprintf(
            output,
            outputSize,
            "%.1f %s",
            value,
            units[unitIndex]);
    }
    else
    {
        result = _snprintf(
            output,
            outputSize,
            "%.2f %s",
            value,
            units[unitIndex]);
    }

    // Older Microsoft implementations of _snprintf may not terminate
    // the output when truncation occurs.
    output[outputSize - 1] = '\0';

    return result >= 0 && (size_t)result < outputSize;
}

// Why the last WriteBody / WriteChunkedBody call failed, for the log. Both
// used to fail with one shared message - "Failed to decode chunked HTTP
// body" - which read the same whether the disk refused a write or the server
// sent something that wasn't valid chunked encoding, and those need entirely
// different fixes.
static char g_bodyError[256] = "";

// "at body offset N (decoder state S...); next bytes: 3F 0D 0A ..." - where the
// stream was when it went wrong, and the bytes it choked on.
static void NoteChunkedError(const char *what, const ChunkedDecodeState *state,
                             const char *data, int pos, int len, unsigned long long totalWritten)
{
    char hex[3 * 16 + 1] = "";
    int n = 0;
    for (int i = pos; i < len && n < 16; ++i, ++n)
        _snprintf(hex + n * 3, 4, "%02X ", (unsigned char)data[i]);
    hex[sizeof(hex) - 1] = '\0';

    // The size line collected so far, as hex too - it's the likeliest place
    // for something that isn't chunked encoding at all (an error page, say)
    // to show itself, and printing it raw would risk non-printable bytes
    // reaching the console renderer.
    char lineHex[3 * 12 + 1] = "";
    for (int i = 0; i < state->sizeLineLen && i < 12; ++i)
        _snprintf(lineHex + i * 3, 4, "%02X ", (unsigned char)state->sizeLine[i]);
    lineHex[sizeof(lineHex) - 1] = '\0';

    _snprintf(g_bodyError, sizeof(g_bodyError), "%s at body offset %I64u (state %d); size line: %s; next bytes: %s",
              what, totalWritten, state->state, lineHex, hex);
    g_bodyError[sizeof(g_bodyError) - 1] = '\0';
}

static bool WriteBody(FILE *file, const char *data, int len, unsigned long long *totalWritten, char *outputBuffer)
{
    if (len <= 0)
        return true;

    if (outputBuffer == NULL)
    {
        if (fwrite(data, 1, len, file) != (size_t)len)
        {
            _snprintf(g_bodyError, sizeof(g_bodyError), "disk write failed at body offset %I64u (errno %d) - is the drive full?",
                      *totalWritten, errno);
            g_bodyError[sizeof(g_bodyError) - 1] = '\0';
            return false;
        }
    }
    else
    {
        memcpy(outputBuffer + outputBufferPointer, data, len);
        outputBufferPointer += len;
    }

    *totalWritten += len;
    return true;
}

static bool WriteChunkedBody(ChunkedDecodeState *state, FILE *file, const char *data, int len, unsigned long long *totalWritten, char *outputBuffer)
{
    int pos = 0;

    while (pos < len && state->state != 3)
    {
        if (state->state == 0)
        {
            char c = data[pos++];

            if (c == '\r')
                continue;

            if (c == '\n')
            {
                unsigned long chunkSize;

                if (!ParseChunkSize(state->sizeLine, state->sizeLineLen, &chunkSize))
                {
                    NoteChunkedError("invalid chunk-size line", state, data, pos - 1, len, *totalWritten);
                    return false;
                }

                state->sizeLineLen = 0;
                state->remaining = chunkSize;

                if (chunkSize == 0)
                    state->state = 3;
                else
                    state->state = 1;

                continue;
            }

            if (state->sizeLineLen >= (int)sizeof(state->sizeLine))
            {
                NoteChunkedError("chunk-size line too long", state, data, pos - 1, len, *totalWritten);
                return false;
            }

            state->sizeLine[state->sizeLineLen++] = c;
        }
        else if (state->state == 1)
        {
            int bytesToWrite = (int)state->remaining;
            int available = len - pos;

            if (bytesToWrite > available)
                bytesToWrite = available;

            if (!WriteBody(file, data + pos, bytesToWrite, totalWritten, outputBuffer))
                return false; // g_bodyError already says why
			
            pos += bytesToWrite;
            state->remaining -= (unsigned long)bytesToWrite;

            if (state->remaining == 0)
                state->state = 2;
        }
        else if (state->state == 2)
        {
            char c = data[pos++];

            if (c == '\n')
                state->state = 0;
            else if (c != '\r')
            {
                NoteChunkedError("chunk data not followed by CRLF", state, data, pos - 1, len, *totalWritten);
                return false;
            }
        }
    }

    return true;
}

unsigned long long parseContentLength(char *headerBuffer, size_t bufferLength)
{
    const char prevChar = headerBuffer[bufferLength - 1];
    headerBuffer[bufferLength - 1] = '\0';
    const char *contentLengthString = strstr(headerBuffer, "Content-Length: ");
    headerBuffer[bufferLength - 1] = prevChar;

    if (contentLengthString == NULL)
    { // no content length found in header
        return 0;
    }

    return _atoi64(contentLengthString + strlen("Content-Length: ")); // atoi should automatically stop when it sees the '\n' char
}

unsigned long long parseStatus(char *headerBuffer, size_t bufferLength)
{
    const char prevChar = headerBuffer[bufferLength - 1];
    headerBuffer[bufferLength - 1] = '\0';
    const char *statusString = strstr(headerBuffer, " ");
    headerBuffer[bufferLength - 1] = prevChar;

    if (statusString == NULL)
    { // no content length found in header
        return 0;
    }

    return _atoi64(statusString + strlen(" ")); // atoi should automatically stop when it sees the '\n' char
}

char *parseLocation(char *headerBuffer, size_t bufferLength, char *redirectURL, size_t urlSize)
{
    if (headerBuffer == NULL || redirectURL == NULL || urlSize == 0 || bufferLength == 0)
    {
        return NULL;
    }

    redirectURL[0] = '\0';

    const char prevChar = headerBuffer[bufferLength - 1];
    headerBuffer[bufferLength - 1] = '\0';
    const char *statusString = strstr(headerBuffer, "Location: ");
    headerBuffer[bufferLength - 1] = prevChar;

    if (statusString == NULL)
    { // no content length found in header
        return NULL;
    }

    const char *src = statusString + strlen("Location: ");

    size_t i = 0;
    while (src[i] != '\0' && src[i] != '\n' && src[i] != '\r')
    {
        if (i + 1 >= urlSize)
        {
            redirectURL[0] = '\0';
            return NULL;
        }

        redirectURL[i] = src[i];
        i++;
    }
    redirectURL[i] = '\0';

    return redirectURL;
}

static bool CopyTextToBuffer(const char *source, char *destination, unsigned long long *destinationSize)
{
    if (source == NULL || destination == NULL || destinationSize == NULL || *destinationSize == 0)
        return false;

    size_t sourceLength = strlen(source);
    size_t capacity = (size_t)*destinationSize;

    if (sourceLength >= capacity)
    {
        destination[0] = '\0';
        return false;
    }

    memcpy(destination, source, sourceLength + 1);
    *destinationSize = (unsigned long long)sourceLength;
    return true;
}

unsigned long long getClockLong()
{
    return (unsigned long long)clock();
}

// Function to check if a string ends with another string
bool endsWith(const std::string &fullString,
              const std::string &ending)
{
    // Check if the ending string is longer than the full
    // string
    if (ending.size() > fullString.size())
        return false;

    // Compare the ending of the full string with the target
    // ending
    return fullString.compare(fullString.size() - ending.size(),
                              ending.size(), ending) == 0;
}

int DumpResponse(XboxTLSContext *ctx,
                 const std::string filename,
                 char *outputBuffer,
                 unsigned long long *outputBufferSize,
                 char *redirectBuffer,
                 unsigned long long *redirectBufferSize,
                 char *cookieOutBuffer,
                 unsigned long long cookieOutBufferSize,
                 void printFunction(const char *_format, ...),
                 unsigned long long knownTotalSize = 0,
                 DownloadProgressFn progressFn = NULL)
{
    unsigned long long outputBufferSizeConst = 0;
    int responseCode = 0; // HTTP status code

    if (outputBuffer != NULL)
    {
        outputBufferSizeConst = *outputBufferSize;
    }

    outputBufferPointer = 0; // Whether writing to a buffer or not, it doesn't hurt to clear this

    const unsigned long long BUFFER_SIZE = 4 * 1024 * 1024;
    const unsigned long long MAX_FILE_SIZE = 0xF0000000;

    char *buffer = (char *)malloc(BUFFER_SIZE);

    if (buffer == NULL)
    {
        ERROR("MALLOC failed");
        return EXIT_FAILURE;
    }

    char *fileBuffer = (char *)malloc(BUFFER_SIZE);

    if (fileBuffer == NULL)
    {
        ERROR("MALLOC failed");
        free(buffer);
        return EXIT_FAILURE;
    }

    char headerBuffer[16 * 1024];
    unsigned long long headerLen = 0;
    bool headersDone = false;
    bool chunked = false;
    ChunkedDecodeState chunkedState;
    int r = 0;

    bool writeToBuffer = false; // should we write to a buffer instead of a file???
    bool splitFile = false;

    if (outputBuffer != NULL)
    {
        writeToBuffer = true;
    }

    FILE *file = NULL;
    if (!writeToBuffer)
    {
        if (endsWith(filename, std::string(".001")))
        {
            splitFile = true;
            std::cout << "Split file detected\n";
        }
        file = fopen(filename.c_str(), "wb");

        if (file == NULL)
        {
            printFunction("Failed to open file %s\n", filename.c_str());
            free(buffer);
            free(fileBuffer);
            return EXIT_FAILURE;
        }
        setvbuf(file, fileBuffer, _IOFBF, BUFFER_SIZE);
    }

    InitChunkedDecodeState(&chunkedState);
    g_bodyError[0] = '\0';

    unsigned long long startTime = (getClockLong() * (unsigned long long)1000) / (CLOCKS_PER_SEC);
    unsigned long long endTime = (getClockLong() * (unsigned long long)1000) / (CLOCKS_PER_SEC);

    // startTime is never reset, so "endTime - startTime" is elapsed time
    // since the WHOLE download began, not since the last print - once that
    // crosses the threshold once, it stays true for every remaining read for
    // the rest of the download (one TLS record, ~16KB, per read), so a large
    // file printed "Speed: ..." on essentially every iteration - tens of
    // thousands of times for a multi-GB file, each one paying for a
    // character-by-character console render plus an open/append/close of
    // the debug log file. lastPrintTime tracks when we last actually
    // printed, so the throttle below is against "time since last print", not
    // "time since download start".
    unsigned long long lastPrintTime = startTime;

    // Separate, much faster throttle for the graphical progress callback than
    // the 2-3 second one lastPrintTime governs for the text prints. A drawn
    // bar needs to move often enough to read as live, but firing it per-read
    // would be far worse than the text prints ever were - progressFn's
    // implementation draws and Present()s a whole frame. ~100ms is smooth
    // enough to look continuous while costing ~10 frames/sec of GPU work.
    unsigned long long lastProgressTime = startTime;
    const unsigned long long PROGRESS_CALLBACK_INTERVAL_MS = 100;

    unsigned long long totalWritten = 0;

    unsigned long long lastBytesWritten = 0;
    unsigned long long KBdownloaded = 0;

    unsigned long long totalContentLength = 0;

    unsigned long long beginTime = startTime;

    unsigned long long bytesWrittenToCurrentFile = 0;

    char *splitFilename = NULL;

    if (!writeToBuffer)
    {
        splitFilename = strdup(filename.c_str());
    }

    while ((!headersDone || writeToBuffer) && (r = XboxTLS_Read(ctx, buffer, BUFFER_SIZE)) > 0)
    {
        const char *body = buffer;
        int bodyLen = r;

        if (!headersDone)
        {
            int copyLen = r;
            int headerEnd;

            if (copyLen > (int)sizeof(headerBuffer) - headerLen)
                copyLen = (int)sizeof(headerBuffer) - headerLen;

            memcpy(headerBuffer + headerLen, buffer, copyLen);
            headerLen += copyLen;

            headerEnd = FindHeaderEnd(headerBuffer, headerLen);
            if (headerEnd < 0)
            {
                if (headerLen >= (int)sizeof(headerBuffer))
                {
                    printFunction("HTTP headers too large\n");
                    goto failure;
                }

                continue;
            }

            const char tempChar = buffer[r - 1];
            buffer[r - 1] = '\0';
            // std::cout << buffer << "\n\n";
            buffer[r - 1] = tempChar;

            headersDone = true;
            chunked = HeaderContainsToken(headerBuffer, headerEnd, "Transfer-Encoding", "chunked");
            body = headerBuffer + headerEnd;
            bodyLen = headerLen - headerEnd;
            totalContentLength = parseContentLength(headerBuffer, headerEnd);

            // archive.org's view_archive.php (used to serve an already-
            // extracted RAR member) streams its response chunked, with no
            // Content-Length at all - so there's normally nothing to show
            // progress/ETA against, or to validate the final size against
            // at the end. We already know the real final size from the
            // RAR header we parsed earlier (member.unpSize), so the caller
            // can pass that in as knownTotalSize to use here instead.
            if (totalContentLength == 0 && knownTotalSize > 0)
                totalContentLength = knownTotalSize;

            int status = parseStatus(headerBuffer, headerEnd);
            responseCode = status; // value to return

            if (cookieOutBuffer != NULL && cookieOutBufferSize > 0)
            {
                ExtractSetCookies(headerBuffer, headerEnd, cookieOutBuffer, cookieOutBufferSize);
            }

            // 206 (Partial Content) is a success status for Range requests;
            // everything else that isn't a plain 200 goes through the same
            // error/redirect handling below.
            if (status != 200 && status != 206)
            {
                printFunction("Status: %d\n", status);
                // A verbatim response-header dump used to live here for an
                // earlier investigation (why a request was getting a 401).
                // Removed: it printed raw response bytes through the
                // console's character-by-character renderer
                // (Display -> Add(CHAR) -> MultiByteToWideChar -> font glyph
                // lookup), and a response containing anything non-printable
                // there is a real crash risk this project can't fully rule
                // out - confirmed suspicious on hardware (blank lines where
                // the dump should have been, then a crash, with a rebuild
                // that only sanitized the copy but not what was fed to the
                // renderer). Not worth re-adding without sanitizing every
                // byte first, and the investigation it was for is done.

                switch (status)
                {
                case 429:
                    printFunction("Error: Too many requests (rate limited)\n");
                    break;
                case 404:
                    printFunction("Error: Page not found\n");
                    break;
                case 302:
                {
                    printFunction("Redirect Found, following\n");
                    char newURL[1024 * 5];
                    char *locResult = parseLocation(headerBuffer, headerEnd, newURL, sizeof(newURL));
                    if (locResult == NULL)
                    {
                        printFunction("ERROR: Location header missing or too long\n");
                        goto failure;
                    }

                    if (redirectBuffer != NULL && redirectBufferSize != NULL)
                    {
                        if (!CopyTextToBuffer(newURL, redirectBuffer, redirectBufferSize))
                        {
                            printFunction("ERROR: Redirect URL buffer too small\n");
                            goto failure;
                        }
                    }
                    else if (writeToBuffer && outputBuffer != NULL && outputBufferSize != NULL)
                    {
                        if (!CopyTextToBuffer(newURL, outputBuffer, outputBufferSize))
                        {
                            printFunction("ERROR: Redirect URL buffer too small\n");
                            goto failure;
                        }
                    }
                    else if (filename.length() > 0 && file != NULL)
                    {
                        fprintf(file, "%s\n", newURL);
                    }
                    else
                    {
                        goto failure;
                    }

                    goto redirectSuccess;
                    break;
                }
                default:
                    break;
                }

                goto failure;
            }
        }

        // Checked here (actual body bytes about to be written, headers
        // already stripped out of bodyLen above) rather than against the raw
        // per-read byte count `r` - the old check compared `r` (which, on
        // the very first read, is headers+body combined straight off the
        // socket) against outputBufferSizeConst, a limit meant for body
        // content only. archive.org's response headers alone (Set-Cookie,
        // Content-Range, etc.) are routinely several hundred bytes, so that
        // comparison overflowed a buffer-mode caller's small Range-request
        // buffer (e.g. 1KB, used to peek RAR headers) on essentially every
        // real request, before a single header had even been parsed
        // (confirmed on hardware: failed immediately with responseCode still
        // at its unset default of 0). WriteBody/WriteChunkedBody have no
        // bounds check of their own, so this guard is still required - just
        // against the right quantity.
        if (writeToBuffer && totalWritten + (unsigned long long)bodyLen > outputBufferSizeConst)
        {
            printFunction("Output Buffer Exhausted\n");
            goto failure;
        }

        if (chunked)
        {
            if (!WriteChunkedBody(&chunkedState, file, body, bodyLen, &totalWritten, outputBuffer))
            {
                printFunction("Chunked HTTP body failed: %s\n", g_bodyError);
                goto failure;
            }
        }
        else if (!WriteBody(file, body, bodyLen, &totalWritten, outputBuffer))
        {
            printFunction("Failed to write to file\n");
            goto failure;
        }

        endTime = (getClockLong() * (unsigned long long)1000) / (CLOCKS_PER_SEC);

        if (endTime - lastPrintTime >= 2000)
        {
            int downloadSpeed = (int)((totalWritten * 1000) / (endTime - startTime));
            printFunction("Speed: %d Bytes/sec \n", downloadSpeed);
            lastPrintTime = endTime;
        }
    }

    // Check for chunked download (unlikely)
    if (chunked && splitFile)
    {
        printFunction("\nERROR: chunked split file not supported yet\n");

        if (file != NULL)
        {
            fclose(file);
        }
        free(buffer);
        free(fileBuffer);
        free(splitFilename);
        return EXIT_FAILURE;
    }

    while (chunked && (r = XboxTLS_Read(ctx, buffer, BUFFER_SIZE)) > 0) // Chunked download
    {
        const char *body = buffer;
        int bodyLen = r;

        if (chunked)
        {
            if (!WriteChunkedBody(&chunkedState, file, body, bodyLen, &totalWritten, outputBuffer))
            {
                printFunction("Chunked HTTP body failed: %s\n", g_bodyError);
                break;
            }
        }

        endTime = (getClockLong() * (unsigned long long)1000) / (CLOCKS_PER_SEC);

        if (endTime - lastPrintTime >= 2000)
        {
            unsigned long long elapsed = endTime - startTime;
            int downloadSpeed = (elapsed > 0) ? (int)((totalWritten * 1000) / elapsed) : 0;

            // Chunked responses (this is the path archive.org's
            // view_archive.php actually uses to serve an already-extracted
            // RAR member - it streams the decompressed data without ever
            // knowing/sending a Content-Length) normally have nothing to
            // show a percentage/ETA against. But DownloadDlcMember passes
            // the real final size in as knownTotalSize (straight from the
            // RAR header we already parsed for this member), which got
            // adopted as totalContentLength above since no Content-Length
            // was present - so we can still show real progress here.
            if (totalContentLength > 0)
            {
                char humanReadableDownloaded[64] = "";
                char humanReadableTotal[64] = "";
                char humanReadableSpeedChunked[64] = "";
                FormatBytes(totalWritten, humanReadableDownloaded, sizeof(humanReadableDownloaded));
                FormatBytes(totalContentLength, humanReadableTotal, sizeof(humanReadableTotal));
                FormatBytes((unsigned long long)downloadSpeed, humanReadableSpeedChunked, sizeof(humanReadableSpeedChunked));

                int percent = (int)((totalWritten * 100) / totalContentLength);
                unsigned long long bytesRemaining = (totalContentLength > totalWritten) ? (totalContentLength - totalWritten) : 0;
                unsigned long long timeRemaining = (downloadSpeed > 0) ? (bytesRemaining / (unsigned long long)downloadSpeed) : 0;

                // "pct" rather than a literal percent sign: "%%" through this
                // logging path prints NOTHING (see LogEscapePercent in
                // parsing.h), which is why this line used to read "(7)"
                // instead of "(7%)". The drawn progress bar still shows a real
                // percent sign - it builds its text with a direct _snprintf,
                // which is a single format pass and handles "%%" correctly.
                printFunction("Downloaded %s out of %s (%d pct), Speed: %s/sec, Time Remaining %llu:%llu:%llu\n",
                              humanReadableDownloaded, humanReadableTotal, percent, humanReadableSpeedChunked,
                              timeRemaining / (unsigned long long)3600, (timeRemaining / (unsigned long long)60) % (unsigned long long)60, timeRemaining % (unsigned long long)60);
            }
            else
            {
                printFunction("Speed: %d Bytes/sec \n", downloadSpeed);
            }

            lastPrintTime = endTime;
        }

        // Graphical progress, on its own faster throttle - deliberately
        // outside the text-print block above so the drawn bar keeps moving
        // between the 2-second text updates.
        if (progressFn != NULL && endTime - lastProgressTime >= PROGRESS_CALLBACK_INTERVAL_MS)
        {
            unsigned long long elapsed = endTime - startTime;
            unsigned long long speed = (elapsed > 0) ? ((totalWritten * 1000) / elapsed) : 0;
            unsigned long long remaining = 0;

            if (totalContentLength > totalWritten && speed > 0)
                remaining = (totalContentLength - totalWritten) / speed;

            if (!progressFn(totalWritten, totalContentLength, speed, remaining))
            {
                printFunction("Download cancelled\n");
                responseCode = HTTP_STATUS_CANCELLED;
                goto failure;
            }
            lastProgressTime = endTime;
        }
    }

    bytesWrittenToCurrentFile = totalWritten;

    if (!chunked) // When dowloading from Vimms lair, we request that the files is NOT chunked, so this loop 99% of the time should be what is used to download the majority of the file (except the header of course!!!)
    {
        while ((r = XboxTLS_Read(ctx, buffer, BUFFER_SIZE)) > 0)
        {
            if (r + bytesWrittenToCurrentFile > MAX_FILE_SIZE && splitFile) // As both XFat and FAT32 only support 4GB files, all downloaded files must be split (file.001, file.002, etc..). Up to 9 parts (.009) is supported
            {
                printFunction("File overflowed, creating next split file part. ");

                size_t bytesThisFile = (size_t)(MAX_FILE_SIZE - bytesWrittenToCurrentFile);
                size_t bytesNextFile = (size_t)r - bytesThisFile;

                if (bytesThisFile > 0 && fwrite(buffer, 1, bytesThisFile, file) != bytesThisFile)
                {
                    printFunction("Failed to write to file\n");
                    goto failure;
                }

                totalWritten += bytesThisFile;
                bytesWrittenToCurrentFile += bytesThisFile;

                fclose(file);

                if (!IncrementSplitFilename(splitFilename))
                {
                    printFunction("\nERROR: failed to increment split filename %s\n\n", splitFilename);
                    break;
                }

                file = fopen(splitFilename, "wb");

                if (file == NULL)
                {
                    printFunction("\nERROR: failed to open %s\n\n", splitFilename);
                    ERROR("Faile to open new split file part");
                    break;
                }
                setvbuf(file, fileBuffer, _IOFBF, BUFFER_SIZE);

                if (bytesNextFile > 0 && fwrite(buffer + bytesThisFile, 1, bytesNextFile, file) != bytesNextFile)
                {
                    printFunction("Failed to write to file\n");
                    break;
                }

                totalWritten += bytesNextFile;
                r = (int)bytesNextFile;
                bytesWrittenToCurrentFile = 0;
                bytesWrittenToCurrentFile += bytesNextFile;

                printFunction("Created new split file part");

                continue;
            }

            if (fwrite(buffer, sizeof(buffer[0]), r, file) < r)
            {
                printFunction("Failed to write to file\n");
                goto failure;
            }

            totalWritten += r;
            bytesWrittenToCurrentFile += r;

            endTime = (getClockLong() * (unsigned long long)1000) / (CLOCKS_PER_SEC);

            // Graphical progress, on its own faster throttle than the text
            // prints below. Deliberately placed BEFORE the 3-second text
            // block rather than inside it, for two reasons: that block's
            // divide-by-zero branch does a `continue`, which would skip this
            // entirely on slow links, and it reassigns startTime as a rolling
            // speed-window marker. beginTime (the real download start, never
            // reassigned) is what gives a stable average speed here.
            if (progressFn != NULL && endTime - lastProgressTime >= PROGRESS_CALLBACK_INTERVAL_MS)
            {
                unsigned long long elapsed = (endTime > beginTime) ? (endTime - beginTime) : 0;
                unsigned long long speed = (elapsed > 0) ? ((totalWritten * 1000) / elapsed) : 0;
                unsigned long long remaining = 0;

                if (totalContentLength > totalWritten && speed > 0)
                    remaining = (totalContentLength - totalWritten) / speed;

                if (!progressFn(totalWritten, totalContentLength, speed, remaining))
                {
                    printFunction("Download cancelled\n");
                    responseCode = HTTP_STATUS_CANCELLED;
                    goto failure;
                }
                lastProgressTime = endTime;
            }

            if (endTime - startTime >= 3000)
            {
                unsigned long long tempTotalWritten = totalWritten;
                if (tempTotalWritten / (endTime - startTime) == 0 || tempTotalWritten / (endTime - beginTime) == 0)
                {
                    std::cout << "Divide by 0 error found\n";
                    // tempTotalWritten++;
                    printFunction("Downloaded %llu KB out of %llu KB, time: %llu\n", tempTotalWritten / (unsigned long long)1024, totalContentLength / (unsigned long long)1024, (endTime - beginTime) / (unsigned long long)1000);

                    endTime = (getClockLong() * (unsigned long long)1000) / (CLOCKS_PER_SEC);
                    startTime = endTime;
                    lastBytesWritten = tempTotalWritten;
                    continue;
                }
                else
                {
                    char humanReadableDownloadedBytes[1024] = "";
                    char humanReadableTotalBytes[1024] = "";
                    char humanReadableSpeed[1024] = "";
                    char humanReadableAverageSpeed[1024] = "";

                    unsigned long long elapsedTime = (endTime - beginTime) / 1000;
                    unsigned long long downloadSpeed = ( (tempTotalWritten - lastBytesWritten) * 1000 ) / (endTime - startTime);
                    unsigned long long averageDownloadSpeed = (tempTotalWritten * 1000) / (endTime - beginTime);
                    unsigned long long bytesRemaining = totalContentLength - tempTotalWritten;
                    unsigned long long timeRemaining = bytesRemaining / averageDownloadSpeed;

                    FormatBytes(tempTotalWritten, humanReadableDownloadedBytes, sizeof(humanReadableDownloadedBytes));
                    FormatBytes(totalContentLength, humanReadableTotalBytes, sizeof(humanReadableDownloadedBytes));
                    FormatBytes(downloadSpeed, humanReadableSpeed, sizeof(humanReadableDownloadedBytes));
                    FormatBytes(averageDownloadSpeed, humanReadableAverageSpeed, sizeof(humanReadableDownloadedBytes));

                    endTime = (getClockLong() * (unsigned long long)1000) / (CLOCKS_PER_SEC);
                    startTime = endTime;
                    lastBytesWritten = tempTotalWritten;
                    printFunction("Downloaded %s out of %s, Speed: %s/s, Average: %s/s, Time %llu s, Time Remaining %llu:%llu:%llu s\n",
                                  humanReadableDownloadedBytes, humanReadableTotalBytes, humanReadableSpeed, humanReadableAverageSpeed, (endTime - beginTime) / (unsigned long long)1000, timeRemaining / (unsigned long long)3600, (timeRemaining / (unsigned long long)60) % (unsigned long long)60, timeRemaining % (unsigned long long)60);
                }
            }
        }
    }

    if (outputBufferSize != NULL)
    {
        *outputBufferSize = totalWritten;
    }

    if (writeToBuffer)
    {
        outputBuffer[totalWritten] = '\0';
    }

    if (totalWritten != totalContentLength && totalContentLength != 0)
    {
        ERROR("Download has likely failed");
        goto failure;
    }

redirectSuccess:

    if (file != NULL)
        fclose(file);

    if (splitFilename != NULL)
        free(splitFilename);

    if (buffer != NULL)
        free(buffer);

    if (fileBuffer != NULL)
        free(fileBuffer);

    return responseCode;

failure:

    if (responseCode == 200)
    {
        responseCode = -1;
    }

    if (file != NULL)
        fclose(file);

    printFunction("Download Failed\n");

    if (splitFilename != NULL)
        free(splitFilename);

    if (buffer != NULL)
        free(buffer);

    if (fileBuffer != NULL)
        free(fileBuffer);

    return responseCode;
}

// The roots every HTTPS connection is checked against - see TrustAnchors.h,
// generated from real certificate files by tools/make_trust_anchors.py.
//
// This used to add six hand-pasted anchors, and two of them could never have
// matched anything: the one labelled "ISRG Root X1" had a malformed name and a
// 2040-bit key belonging to no certificate, and the others were intermediates
// (Let's Encrypt E7 and R12, a Sectigo one for GitHub) that archive.org
// doesn't serve and that expire. None of that mattered while the TLS library
// was patched to accept untrusted chains anyway - it isn't any more.
int addTrustAnchors(XboxTLSContext *ctx)
{
    // The hash BearSSL's X.509 engine uses to compare distinguished names.
    // Not a certificate property: any hash works, since both sides of each
    // comparison are hashed here on the console.
    ctx->hashAlgo = XboxTLS_Hash_SHA384;

    for (unsigned long i = 0; i < TRUST_ANCHOR_COUNT; ++i)
    {
        const TrustAnchorDef &ta = kTrustAnchors[i];

        bool added = ta.isEc
            ? XboxTLS_AddTrustAnchor_EC(ctx, ta.dn, ta.dnLen, ta.ecQ, ta.ecQLen, (XboxTLSCurve)ta.ecCurve)
            : XboxTLS_AddTrustAnchor_RSA(ctx, ta.dn, ta.dnLen, ta.rsaN, ta.rsaNLen, ta.rsaE, ta.rsaELen);

        if (!added)
            return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}

int downloadFileHTTPS(const std::string URL, const std::string fileName, char *dataBuffer, unsigned long long *outputBufferSize, bool downloadIntoFile, void printFunction(const char *_format, ...))
{
    return httpRequestHTTPS(URL, HTTP_GET, NULL, NULL, fileName, dataBuffer, outputBufferSize, downloadIntoFile, NULL, 0, printFunction);
}

int httpRequestHTTPS(const std::string URL, HttpMethod method, const char *requestBody,
                     const char *extraHeaderLines, const std::string fileName,
                     char *dataBuffer, unsigned long long *outputBufferSize, bool downloadIntoFile,
                     char *cookieOutBuffer, unsigned long long cookieOutBufferSize,
                     void printFunction(const char *_format, ...),
                     unsigned long long knownTotalSize,
                     DownloadProgressFn progressFn)
{
    char *domain;
    char *path;

    int httpStatus = 0;

    // Escaped before logging: a percent-encoded URL printed raw comes out
    // mangled (see LogEscapePercent in parsing.h). This is the single most
    // important place for it - every request logs its URL here, and a wrong
    // one sends you hunting an encoding bug that doesn't exist.
    {
        char safeUrl[1024];
        LogEscapePercent(URL.c_str(), safeUrl, sizeof(safeUrl));
        printFunction("Attempting to download: %s\n", safeUrl);
    }

    if ((domain = (char *)malloc(URL.length() + 1)) == NULL)
    {
        ERROR("MALLOC failed");
        return false;
    }
    if ((path = (char *)malloc(URL.length() + 1)) == NULL)
    {
        ERROR("MALLOC failed");
        free(domain);
        return false;
    }

    if (parseURL(URL.c_str(), domain, path) != 0)
    {
        std::cout << "ERROR parsing URL\n\n";
        free(domain);
        free(path);
        return false;
    }

    // Step 1: Network stack setup
    XNetStartupParams xnsp = {0};
    xnsp.cfgSizeOfStruct = sizeof(xnsp);
    xnsp.cfgFlags = XNET_STARTUP_BYPASS_SECURITY;
    if (XNetStartup(&xnsp) != 0)
    {
        ERROR("Couldn't initialize network stack");
        free(domain);
        free(path);
        return false;
    }

    WSADATA wsadata;
    if (WSAStartup(MAKEWORD(2, 2), &wsadata) != 0)
    {
        ERROR("Couldn't start WSA");
        XNetCleanup();
        free(domain);
        free(path);
        return false;
    }

    // Step 2: Create TLS context
    XboxTLSContext ctx;
    if (!XboxTLS_CreateContext(&ctx, domain))
    {
        ERROR("Couldn't create TLS context");
        XNetCleanup();
        WSACleanup();
        free(domain);
        free(path);
        return false;
    }

    if (addTrustAnchors(&ctx) != EXIT_SUCCESS)
    {
        ERROR("Couldn't add trust anchor");
        XboxTLS_Free(&ctx);
        WSACleanup();
        XNetCleanup();

        free(domain);
        free(path);
        return false;
    }

    // Step 4: DNS resolution
    printFunction("Resolving DNS\n");
    char ip[64] = {0};

    for (int i = 0; i < 5; i++) // try DNS 5 times until it works.
    {
        if (ip[0] != '\0')
        {
            break;
        }

        ip[0] = '\0';

        if (ResolveDNS(domain, ip, sizeof(ip)))
        {
            printFunction("Init: DNS resolved %s -> %s\n", domain, ip);
            break;
        }

        printFunction("Failed to resolve %s\n", domain);

        if (searchDnsCache(domain, ip, sizeof(ip)) == 0)
        {
            break; // found a cached DNS address.
        }

        WSACleanup();
        XNetCleanup();

        XNetStartup(&xnsp);
        WSAStartup(MAKEWORD(2, 2), &wsadata);
        Sleep(3000);
    }

    if (ip[0] == 0)
    {
        ERROR("Failed to resolve DNS");
        goto downloadFailed;
    }

    log_printf("Attempting to connect to server over TLS 1.2\n\n");
    // Step 5: Connect + TLS handshake
    if (!XboxTLS_Connect(&ctx, ip, domain, 443))
    {
        log_printf("TLS connection failed\n");
        goto downloadFailed;
    }

    // Step 6: Send GET/POST request
    char request[1024 * 5];
    int requestLen;
    int bodyContentLen = (requestBody != NULL) ? (int)strlen(requestBody) : 0;

    char bodyHeaders[256] = "";
    if (bodyContentLen > 0)
    {
        _snprintf(bodyHeaders, sizeof(bodyHeaders),
                 "Content-Type: application/x-www-form-urlencoded\r\n"
                 "Content-Length: %d\r\n",
                 bodyContentLen);
    }

    requestLen = _snprintf(request, sizeof(request),
                           "%s %s HTTP/1.1\r\n"
                           "Host: %s\r\n"
                           "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36\r\n"
                           "Accept: */*\r\n"
                           "Accept-Encoding: identity, *;q=0\r\n"
                           "Connection: close\r\n"
                           "%s" // caller-supplied extra header lines, each ending "\r\n" (Cookie, Range, ...)
                           "%s" // Content-Type + Content-Length, only present for POST with a body
                           "\r\n"
                           "%s", // request body, only present for POST
                           (method == HTTP_POST) ? "POST" : "GET",
                           path, domain,
                           (extraHeaderLines != NULL) ? extraHeaderLines : "",
                           bodyHeaders,
                           (requestBody != NULL) ? requestBody : "");

    if (requestLen < 0 || requestLen >= (int)sizeof(request))
    {
        ERROR("HTTP request buffer too small");
        goto downloadFailed;
    }

    if (XboxTLS_Write(&ctx, request, requestLen) < 0)
    {
        ERROR("Failed to send HTTPS request");
        goto downloadFailed;
    }
    printFunction("Request: sent %d bytes\n", requestLen);

    // Step 7: Read and print response
    if (downloadIntoFile)
    {
        if ((httpStatus = DumpResponse(&ctx, fileName, NULL, NULL, dataBuffer, outputBufferSize, cookieOutBuffer, cookieOutBufferSize, printFunction, knownTotalSize, progressFn)) != 200 && httpStatus != 206)
        {
            if (httpStatus != 302)
            {
                ERROR("Failed to download data over HTTPS");
            }
            goto downloadFailed;
        }
    }
    else
    {
        if ((httpStatus = DumpResponse(&ctx, "", dataBuffer, outputBufferSize, dataBuffer, outputBufferSize, cookieOutBuffer, cookieOutBufferSize, printFunction, knownTotalSize, progressFn)) != 200 && httpStatus != 206)
        {
            if (httpStatus != 302)
            {
                ERROR("Failed to download data over HTTPS");
            }
            goto downloadFailed;
        }
    }

    // Step 8: Cleanup
    XboxTLS_Free(&ctx);
    WSACleanup();
    XNetCleanup();

    free(domain);
    free(path);

    return httpStatus;

downloadFailed:
    XboxTLS_Free(&ctx);
    WSACleanup();

    XNetCleanup();

    free(domain);
    free(path);

    return httpStatus;
}

// ---------------------------------------------------------------------------
// Reusable connections - see HttpsSession in downloadFile.h
// ---------------------------------------------------------------------------
//
// Written alongside httpRequestHTTPS rather than by reworking it, on purpose:
// that function carries every real download, and it works. The connection
// setup below repeats its steps (TLS context, trust anchors, DNS, connect)
// rather than moving them into a shared helper, so none of its paths change.

struct HttpsSession
{
    XboxTLSContext ctx;
    bool connected;
    char host[256];
    HttpStream stream; // this connection's incoming bytes; reset on every new connection

    void (*print)(const char *_format, ...);

    // For the log line on close - the whole point is fewer connections, so
    // it's worth being able to see how many there were.
    int connectionsOpened;
    int requestsSent;
};

static int SessionRead(void *context, char *buf, int len)
{
    return XboxTLS_Read((XboxTLSContext *)context, buf, len);
}

static void SessionDisconnect(HttpsSession *s)
{
    if (s->connected)
    {
        XboxTLS_Free(&s->ctx);
        s->connected = false;
    }
    s->host[0] = '\0';
}

static bool SessionConnect(HttpsSession *s, const char *domain)
{
    if (strlen(domain) >= sizeof(s->host))
        return false;

    if (!XboxTLS_CreateContext(&s->ctx, domain))
    {
        ERROR("Couldn't create TLS context");
        return false;
    }

    if (addTrustAnchors(&s->ctx) != EXIT_SUCCESS)
    {
        ERROR("Couldn't add trust anchor");
        XboxTLS_Free(&s->ctx);
        return false;
    }

    // Same lookup as httpRequestHTTPS, minus its network-stack restart
    // between attempts: the session holds the stack up for its whole life,
    // so restarting it here would pull it out from under the session.
    char ip[64] = "";
    for (int attempt = 0; attempt < 3 && ip[0] == '\0'; ++attempt)
    {
        if (ResolveDNS(domain, ip, sizeof(ip)))
            break;
        ip[0] = '\0';
        if (searchDnsCache(domain, ip, sizeof(ip)) == 0)
            break;
        ip[0] = '\0';
        Sleep(1000);
    }

    if (ip[0] == '\0')
    {
        s->print("[https] could not resolve %s\n", domain);
        XboxTLS_Free(&s->ctx);
        return false;
    }

    if (!XboxTLS_Connect(&s->ctx, ip, domain, 443))
    {
        s->print("[https] could not connect to %s\n", domain);
        XboxTLS_Free(&s->ctx);
        return false;
    }

    memcpy(s->host, domain, strlen(domain) + 1);
    s->connected = true;
    s->connectionsOpened++;
    HttpStreamInit(&s->stream, SessionRead, &s->ctx);
    return true;
}

HttpsSession *HttpsSessionOpen(void printFunction(const char *_format, ...))
{
    HttpsSession *s = (HttpsSession *)malloc(sizeof(HttpsSession));
    if (s == NULL)
        return NULL;

    memset(s, 0, sizeof(*s));
    s->print = printFunction;

    // Brought up once for the session, where httpRequestHTTPS does it per
    // request. Both are reference-counted, so this nests safely with any
    // other request made while the session is open.
    XNetStartupParams xnsp = {0};
    xnsp.cfgSizeOfStruct = sizeof(xnsp);
    xnsp.cfgFlags = XNET_STARTUP_BYPASS_SECURITY;
    if (XNetStartup(&xnsp) != 0)
    {
        free(s);
        return NULL;
    }

    WSADATA wsadata;
    if (WSAStartup(MAKEWORD(2, 2), &wsadata) != 0)
    {
        XNetCleanup();
        free(s);
        return NULL;
    }

    return s;
}

void HttpsSessionClose(HttpsSession *session)
{
    if (session == NULL)
        return;

    SessionDisconnect(session);
    session->print("[https] session done: %d request(s) over %d connection(s)\n",
                   session->requestsSent, session->connectionsOpened);

    WSACleanup();
    XNetCleanup();
    free(session);
}

int HttpsSessionGet(HttpsSession *session, const std::string &url, const char *extraHeaderLines,
                    char *dataBuffer, unsigned long long *dataBufferSize)
{
    if (session == NULL || dataBuffer == NULL || dataBufferSize == NULL)
        return 0;

    std::vector<char> domainBuf(url.length() + 1), pathBuf(url.length() + 1);
    char *domain = &domainBuf[0];
    char *path = &pathBuf[0];

    if (parseURL(url.c_str(), domain, path) != 0)
    {
        session->print("[https] could not parse URL\n");
        return 0;
    }

    {
        char safeUrl[1024];
        LogEscapePercent(url.c_str(), safeUrl, sizeof(safeUrl));
        session->print("[https] GET %s\n", safeUrl);
    }

    const unsigned long long capacity = *dataBufferSize;
    int status = 0;

    // At most two tries, and the second only when the first went over a
    // REUSED connection. A kept-open connection can be closed by the server
    // at any moment it's idle, and the first sign of that is this request
    // failing - so one retry on a fresh connection is the normal cost of
    // reuse, not an error. These are GETs, so repeating one is harmless.
    for (int attempt = 0; attempt < 2; ++attempt)
    {
        const bool reusing = session->connected && _stricmp(session->host, domain) == 0;

        if (session->connected && !reusing)
            SessionDisconnect(session); // a different host; connections are per host

        if (!session->connected)
        {
            if (!SessionConnect(session, domain))
                return 0;
            session->print("[https]   new connection to %s\n", domain);
        }
        else
        {
            session->print("[https]   reusing connection to %s\n", domain);
        }

        // Identical to httpRequestHTTPS's request apart from "keep-alive",
        // which is the one header this whole mechanism turns on.
        char request[1024 * 5];
        int requestLen = _snprintf(request, sizeof(request),
                                   "GET %s HTTP/1.1\r\n"
                                   "Host: %s\r\n"
                                   "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36\r\n"
                                   "Accept: */*\r\n"
                                   "Accept-Encoding: identity, *;q=0\r\n"
                                   "Connection: keep-alive\r\n"
                                   "%s"
                                   "\r\n",
                                   path, domain, (extraHeaderLines != NULL) ? extraHeaderLines : "");

        if (requestLen < 0 || requestLen >= (int)sizeof(request))
        {
            ERROR("HTTP request buffer too small");
            return 0;
        }

        if (XboxTLS_Write(&session->ctx, request, requestLen) < 0)
        {
            SessionDisconnect(session);
            if (reusing && attempt == 0)
            {
                session->print("[https]   connection had closed; retrying on a new one\n");
                continue;
            }
            return 0;
        }

        session->requestsSent++;

        HttpResponseResult response;
        if (!ReadHttpResponse(&session->stream, dataBuffer, capacity, &response))
        {
            SessionDisconnect(session);
            if (reusing && attempt == 0)
            {
                session->print("[https]   no usable response on the reused connection; retrying on a new one\n");
                continue;
            }
            session->print("[https]   response could not be read (status %d)\n", response.status);
            return 0;
        }

        if (!response.keepAlive)
            SessionDisconnect(session); // the server is closing it, or its framing ruled reuse out

        status = response.status;

        if (status == 302)
        {
            // Same contract as DumpResponse in buffer mode: a redirect's
            // target comes back in the data buffer, for the caller to follow.
            size_t locLen = strlen(response.location);
            if (locLen == 0 || locLen >= capacity)
            {
                session->print("[https]   redirect with no usable Location\n");
                return 0;
            }
            memcpy(dataBuffer, response.location, locLen + 1);
            *dataBufferSize = locLen;
        }
        else if (status == 200 || status == 206)
        {
            if (response.bodyOverflow)
            {
                // DumpResponse's "Output Buffer Exhausted" - but reported as
                // a failure, where DumpResponse still handed back the 206.
                session->print("[https]   response larger than the buffer (%I64u bytes)\n", capacity);
                return -1;
            }
            *dataBufferSize = response.bodyLen;
        }
        else
        {
            session->print("Status: %d\n", status);
        }

        break;
    }

    return status;
}
