"""Generates Wordmark.h: the startup screen's "Omni360", baked to images.

XUI draws text from a glyph cache that, at the startup screen's size, cuts
every letter off at the baseline - the bottoms of the O, 3, 6 and 0, which
dip just below it, came out flat. Small text dips by under half a pixel, so
nothing else shows it. So the wordmark is rendered here instead, from the
same Media/Fonts/selawkb.ttf, antialiased, and drawn on the console as
textured quads: the O, which the dot rolls round, and "mni360", which slides
out of it - as "mni" and "360", because PngDecode.cpp caps a side at 512
pixels.

Rendered at a 150px em, the size the startup screen draws it at 1080p, so
there it's pixel for pixel; at 720p it's scaled down. Each image is white
with the glyphs' coverage as alpha, and carries where its pen and baseline
are, so the console can place it exactly.

Run from the repo root:  python tools/make_wordmark.py
"""

import io
import os

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = os.path.join(ROOT, 'Media', 'Fonts', 'selawkb.ttf')
OUTPUT = os.path.join(ROOT, 'src', 'Wordmark.h')

EM = 150   # pixels
PAD = 2    # clear pixels round the ink, so filtering never reaches the edge
MAX_SIDE = 512


def render(font, text):
    """The text's ink, white on clear, and where its pen and baseline sit."""
    left, top, right, bottom = font.getbbox(text, anchor='ls')
    w, h = right - left + PAD * 2, bottom - top + PAD * 2
    assert w <= MAX_SIDE and h <= MAX_SIDE, f'{text!r} is {w}x{h}, over {MAX_SIDE}'
    pen_x, baseline_y = PAD - left, PAD - top
    mask = Image.new('L', (w, h), 0)
    ImageDraw.Draw(mask).text((pen_x, baseline_y), text, font=font, fill=255, anchor='ls')
    image = Image.new('RGBA', (w, h), (255, 255, 255, 0))
    image.putalpha(mask)
    out = io.BytesIO()
    image.save(out, 'PNG', optimize=True)
    return out.getvalue(), w, h, pen_x, baseline_y


def c_array(name, data):
    lines = [f'static const unsigned char {name}[] = {{']
    for i in range(0, len(data), 20):
        lines.append('    ' + ', '.join(f'0x{b:02X}' for b in data[i:i + 20]) + ',')
    lines.append('};')
    lines.append(f'static const unsigned long {name}Size = {len(data)};')
    return '\n'.join(lines)


# The pieces, and the names they have in the header. "mni360" is two only
# because it's wider than 512 pixels; the console slides them together.
PARTS = [('O', 'O'), ('mni', 'MNI'), ('360', 'DIGITS')]
WORD = 'Omni360'


def main():
    font = ImageFont.truetype(FONT, EM)
    defines, arrays, report = [], [], []
    for text, name in PARTS:
        png, w, h, pen_x, baseline_y = render(font, text)
        # The piece's pen, from the word's - as the font sets the word,
        # kerning and all.
        at = font.getlength(WORD) - font.getlength(WORD[WORD.index(text):])
        defines += [
            f'#define WORDMARK_{name}_AT       {at:.2f}f',
            f'#define WORDMARK_{name}_W        {w}',
            f'#define WORDMARK_{name}_H        {h}',
            f'#define WORDMARK_{name}_PEN_X    {pen_x}.0f',
            f'#define WORDMARK_{name}_BASELINE {baseline_y}.0f',
            '',
        ]
        array_name = 'kWordmark' + name.capitalize() + 'Png'
        arrays.append(c_array(array_name, png))
        report.append(f'{text} {w}x{h} at {at:.1f} ({len(png)} bytes)')

    defines_text = '\n'.join(defines)
    arrays_text = '\n\n'.join(arrays)
    header = f'''// Generated by tools/make_wordmark.py - don't edit; run it again.
//
// The startup screen's "Omni360" in Selawik Bold at a {EM}px em, in pieces.
// White, with coverage as alpha. A piece's _AT is where its pen sits after
// the word's; its _PEN_X and _BASELINE are in its own pixels, from its
// top-left.

#ifndef WORDMARK_H
#define WORDMARK_H

#define WORDMARK_EM      {EM}.0f
#define WORDMARK_ADVANCE {font.getlength(WORD):.2f}f // the whole word's

{defines_text}
{arrays_text}

#endif
'''
    with open(OUTPUT, 'w', newline='\r\n') as f:
        f.write(header)
    print(', '.join(report) + f' -> {os.path.relpath(OUTPUT, ROOT)}')


if __name__ == '__main__':
    main()
