"""Generates BoxArtBanner.h: Media/BoxArtBanner.png compiled into the XEX.

The banner down the left of every box art tile - green at the top, "XBOX 360"
reading upwards, the logo at the foot. It replaces the header strip each
cover's own case insert carries, which changed design over the console's life,
so every tile matches whichever era its case came from.

It's 94 x 512: in the 512 x 512 tile, the banner takes the left 94 pixels and
the front of the case the other 418 (CoverArt.h's COVER_BANNER_W and
COVER_FRONT_W). The PNG is stored as it is and decoded at startup by
PngDecode.cpp, the same way the button atlas is.

Run from the repo root:  python tools/make_box_banner.py
"""

import os
import struct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, 'Media', 'BoxArtBanner.png')
OUTPUT = os.path.join(ROOT, 'src', 'BoxArtBanner.h')

EXPECTED = (94, 512)

png = open(SOURCE, 'rb').read()
if png[:8] != b'\x89PNG\r\n\x1a\n':
    raise SystemExit('%s is not a PNG' % SOURCE)

width, height = struct.unpack('>II', png[16:24])
if (width, height) != EXPECTED:
    raise SystemExit('%s is %dx%d; it has to be %dx%d' % ((SOURCE, width, height) + EXPECTED))

lines = [
    '// GENERATED by tools/make_box_banner.py - do not edit by hand; edit',
    '// Media/BoxArtBanner.png and re-run the script.',
    '//',
    '// The banner down the left of every box art tile, as PNG bytes.',
    '',
    '#ifndef BOX_ART_BANNER_H',
    '#define BOX_ART_BANNER_H',
    '',
    '#define BOX_ART_BANNER_WIDTH  %d' % width,
    '#define BOX_ART_BANNER_HEIGHT %d' % height,
    '',
    'static const unsigned long kBoxArtBannerPngSize = %d;' % len(png),
    'static const unsigned char kBoxArtBannerPng[%d] =' % len(png),
    '{',
]
for i in range(0, len(png), 16):
    lines.append('    ' + ', '.join('0x%02X' % b for b in png[i:i + 16]) + ',')
lines += ['};', '', '#endif', '']

open(OUTPUT, 'w', newline='\r\n').write('\n'.join(lines))
print('wrote %s (%d bytes of PNG)' % (OUTPUT, len(png)))
