"""Generates SelawikBold.h: Media/Fonts/selawkb.ttf as a byte array.

The bold face used to travel as a fourth XEX section beside the regular one,
like selawk.ttf does. On hardware the XEX then never reached main() - nothing
was logged at all - and taking that section out again fixed it. Rather than
depend on whatever limit that ran into, the bold face is compiled in as data,
the way the button art is (see make_button_atlas.py), and UiText.cpp writes it
out to a file beside the XEX for XUI to load.

The font is copied byte for byte, so it is still Selawik Bold under the SIL
Open Font License; the licence text already travels in the XEX as the "ofl"
section.

Run from the repo root:  python tools/make_bold_font.py
"""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, 'Media', 'Fonts', 'selawkb.ttf')
OUTPUT = os.path.join(ROOT, 'src', 'SelawikBold.h')

data = open(SOURCE, 'rb').read()

lines = [
    '// GENERATED by tools/make_bold_font.py - do not edit by hand; re-run the',
    '// script. Media/Fonts/selawkb.ttf (Selawik Bold, SIL Open Font License),',
    '// byte for byte. See the script for why it is compiled in.',
    '',
    '#ifndef SELAWIK_BOLD_H',
    '#define SELAWIK_BOLD_H',
    '',
    'static const unsigned long kSelawikBoldTtfSize = %d;' % len(data),
    '',
    'static const unsigned char kSelawikBoldTtf[%d] =' % len(data),
    '{',
]
for i in range(0, len(data), 16):
    lines.append('    ' + ', '.join('0x%02X' % b for b in data[i:i + 16]) + ',')
lines += ['};', '', '#endif', '']

open(OUTPUT, 'w', newline='\r\n').write('\n'.join(lines))
print('wrote %s (%d bytes of font)' % (OUTPUT, len(data)))
