"""
Builds TrustAnchors.h - the root certificates Omni360 trusts for HTTPS - from
the PEM files in tools/trust-anchors/.

    python tools/make_trust_anchors.py

The console has no certificate store, so trusted roots are compiled in. They
used to be hand-pasted hex, and two of those were wrong: the entry labelled
"ISRG Root X1" had a malformed name and a 2040-bit key that belongs to no
certificate at all, so no Let's Encrypt chain could ever reach it. Generating
the table from the real certificate files is what stops that recurring.

Where the PEM files came from, and how they were checked (Sep 2026):
  - ISRG_Root_X1.pem, ISRG_Root_X2.pem, Go_Daddy_Root_G2.pem: Mozilla's root
    store, as extracted by curl (curl.se/ca/cacert.pem, "as of Sep 25 2026").
  - X1 and Go Daddy G2 are byte-identical to the copies in the Windows root
    store. X2 isn't in that store; its key matches the X2 cross-certificate
    archive.org's servers send, and that cross-certificate verifies against X1.

Why these three: they are the roots every chain archive.org serves leads to.
archive.org, its US storage nodes and s3.us.archive.org chain to Go Daddy G2;
its Canadian nodes use Let's Encrypt, whose chains lead to ISRG X2 and X1.
Add a PEM here and re-run if archive.org ever moves to another CA.

And a fourth, for the update check (Oct 2026):
  - USERTrust_ECC.pem: USERTrust ECC Certification Authority, exported from
    the Windows root store (SHA-256 4FF460D5...D2A9AD7A, as Mozilla's store
    lists it). api.github.com chains to it through Sectigo's Public Server
    Authentication Root E46 cross-certificate; the whole chain the server
    sends verified against this root alone with `openssl verify`. GitHub's
    release downloads (objects/release-assets.githubusercontent.com) chain to
    ISRG X1, already here.

For each certificate this emits what BearSSL's br_x509_trust_anchor needs:
the subject DN, exactly as DER-encoded in the certificate (BearSSL compares
DNs byte for byte against each issuer), and the public key - an RSA modulus
and exponent, or an EC point and curve.
"""
import base64, glob, hashlib, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PEM_DIR = os.path.join(ROOT, "tools", "trust-anchors")
OUT = os.path.join(ROOT, "TrustAnchors.h")

OID_RSA = bytes.fromhex("2a864886f70d010101")
CURVES = {  # named-curve OIDs -> BearSSL curve ids (bearssl_ec.h)
    bytes.fromhex("2a8648ce3d030107"): ("BR_EC_secp256r1", 23),
    bytes.fromhex("2b81040022"): ("BR_EC_secp384r1", 24),
    bytes.fromhex("2b81040023"): ("BR_EC_secp521r1", 25),
}


def tlv(b, i):
    """One DER element at b[i]: (tag, whole element, contents, index after)."""
    tag = b[i]
    l = b[i + 1]
    j = i + 2
    if l & 0x80:
        n = l & 0x7F
        l = int.from_bytes(b[j:j + n], "big")
        j += n
    return tag, b[i:j + l], b[j:j + l], j + l


def children(content):
    i, out = 0, []
    while i < len(content):
        tag, whole, inner, i = tlv(content, i)
        out.append((tag, whole, inner))
    return out


def parse(pem_text):
    der = base64.b64decode("".join(l for l in pem_text.splitlines() if l and not l.startswith("-----")))
    cert = children(tlv(der, 0)[2])
    tbs = children(cert[0][2])
    k = 1 if tbs[0][0] == 0xA0 else 0         # optional explicit version
    subject_der = tbs[k + 4][1]               # serial, signature alg, issuer, validity, SUBJECT
    validity = children(tbs[k + 3][2])
    spki = children(tbs[k + 5][2])
    alg = children(spki[0][2])
    bits = spki[1][2][1:]                     # BIT STRING minus its unused-bits byte

    info = {"subject": subject_der, "sha256": hashlib.sha256(der).hexdigest(),
            "not_after": validity[1][2].decode()}
    if alg[0][2] == OID_RSA:
        rsa = children(tlv(bits, 0)[2])
        info.update(kind="rsa", n=rsa[0][2].lstrip(b"\0"), e=rsa[1][2].lstrip(b"\0"))
    else:
        curve = CURVES[alg[1][2]]
        info.update(kind="ec", q=bits, curve=curve)
    return info


def cn(subject_der):
    for rdn in children(tlv(subject_der, 0)[2]):
        for atv in children(rdn[2]):
            parts = children(atv[2])
            if parts[0][2] == bytes.fromhex("550403"):
                return parts[1][2].decode("utf-8")
    return "?"


def c_array(name, data):
    rows = ["    " + ", ".join("0x%02X" % b for b in data[i:i + 12]) + "," for i in range(0, len(data), 12)]
    return "static const unsigned char %s[%d] =\n{\n%s\n};\n" % (name, len(data), "\n".join(rows))


def main():
    certs = []
    for path in sorted(glob.glob(os.path.join(PEM_DIR, "*.pem"))):
        info = parse(open(path).read())
        info["id"] = os.path.splitext(os.path.basename(path))[0].upper()
        info["file"] = os.path.basename(path)
        certs.append(info)

    lines = [
        "// GENERATED by tools/make_trust_anchors.py from tools/trust-anchors/*.pem -",
        "// do not edit by hand; add or replace a PEM there and re-run it. The script's",
        "// docstring says where each certificate came from and how it was checked.",
        "//",
        "// The root certificates Omni360 trusts for HTTPS. Included by downloadFile.cpp",
        "// only; addTrustAnchors walks kTrustAnchors.",
        "",
        "#ifndef TRUST_ANCHORS_H",
        "#define TRUST_ANCHORS_H",
        "",
    ]
    for c in certs:
        lines.append("// %s  (%s)" % (cn(c["subject"]), c["file"]))
        lines.append("//   SHA-256 %s" % c["sha256"])
        lines.append("//   valid until %s" % c["not_after"])
        lines.append(c_array(c["id"] + "_DN", c["subject"]))
        if c["kind"] == "rsa":
            lines.append(c_array(c["id"] + "_RSA_N", c["n"]))
            lines.append(c_array(c["id"] + "_RSA_E", c["e"]))
        else:
            lines.append(c_array(c["id"] + "_EC_Q", c["q"]))

    lines += [
        "struct TrustAnchorDef",
        "{",
        "    const char *name;",
        "    const unsigned char *dn;  unsigned long dnLen;",
        "    bool isEc;",
        "    const unsigned char *rsaN; unsigned long rsaNLen;  // RSA",
        "    const unsigned char *rsaE; unsigned long rsaELen;",
        "    const unsigned char *ecQ;  unsigned long ecQLen;   // EC",
        "    int ecCurve;                                       // BearSSL curve id",
        "};",
        "",
        "static const TrustAnchorDef kTrustAnchors[] =",
        "{",
    ]
    for c in certs:
        i = c["id"]
        if c["kind"] == "rsa":
            lines.append('    { "%s", %s_DN, sizeof(%s_DN), false, %s_RSA_N, sizeof(%s_RSA_N), %s_RSA_E, sizeof(%s_RSA_E), 0, 0, 0 },'
                         % (cn(c["subject"]), i, i, i, i, i, i))
        else:
            lines.append('    { "%s", %s_DN, sizeof(%s_DN), true, 0, 0, 0, 0, %s_EC_Q, sizeof(%s_EC_Q), %d }, // %s'
                         % (cn(c["subject"]), i, i, i, i, c["curve"][1], c["curve"][0]))
    lines += ["};", "", "#define TRUST_ANCHOR_COUNT (sizeof(kTrustAnchors) / sizeof(kTrustAnchors[0]))", "", "#endif", ""]

    with open(OUT, "w", newline="\r\n") as f:
        f.write("\n".join(lines))
    for c in certs:
        print("%-45s %s  until %s" % (cn(c["subject"]), c["kind"], c["not_after"]))
    print("wrote", os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
