"""
Builds TitleNames.h: Xbox 360 title IDs and game names, compiled into the XEX
so a disc being installed can be named without a network lookup.

    python tools/make_title_names.py

The list is iso2god-rs's titles.jsonl (https://github.com/iliazeus/iso2god-rs,
MIT - notice reproduced in the generated file), itself a dump of XboxUnity's
community database. Names there are user-submitted and sometimes informal
("Spidey: Web of Shadows"), which is why the install flow only uses a name to
prefill the keyboard rather than writing it straight into the package.

Pinned to one commit, so re-running gives the same header. Only 360 titles are
kept: original Xbox discs aren't converted yet, and arcade titles never come
on a disc.
"""
import json
import os
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_HEADER = os.path.join(ROOT, "src", "TitleNames.h")

COMMIT = "1ae8591280bacde07c1488be1c26e7d360b157de"
URL = "https://raw.githubusercontent.com/iliazeus/iso2god-rs/%s/src/game_list/titles.jsonl" % COMMIT
LICENSE_URL = "https://raw.githubusercontent.com/iliazeus/iso2god-rs/%s/LICENSE" % COMMIT


def c_string(s):
    """A C string literal for UTF-8 text. Octal escapes, not hex: a hex escape
    runs on through any hex digits after it, so "\\xA2a" would be one char."""
    out = []
    for b in s.encode("utf-8"):
        ch = chr(b)
        if ch in '"\\?':          # ? too, so "??" can't form a trigraph
            out.append("\\" + ch)
        elif 0x20 <= b < 0x7F:
            out.append(ch)
        else:
            out.append("\\%03o" % b)
    return '"' + "".join(out) + '"'


def main():
    rows = [json.loads(line) for line in urllib.request.urlopen(URL).read().decode("utf-8").splitlines() if line.strip()]
    licence = urllib.request.urlopen(LICENSE_URL).read().decode("utf-8").strip()

    titles = {}
    for r in rows:
        if r.get("TitleType") != "360":
            continue
        name = " ".join(r["Name"].split())    # trim, and fold runs of spaces
        if name:
            titles[int(r["TitleID"], 16)] = name

    lines = []
    lines.append("// GENERATED by tools/make_title_names.py - do not edit by hand.")
    lines.append("//")
    lines.append("// Xbox 360 title IDs and names, sorted by ID for LookupTitleName's binary")
    lines.append("// search. Names are UTF-8. From iso2god-rs's titles.jsonl at commit")
    lines.append("// %s, under this licence:" % COMMIT)
    lines.append("//")
    for l in licence.splitlines():
        lines.append(("// " + l).rstrip())
    lines.append("")
    lines.append("#ifndef TITLE_NAMES_H")
    lines.append("#define TITLE_NAMES_H")
    lines.append("")
    lines.append("struct TitleNameEntry")
    lines.append("{")
    lines.append("    unsigned long titleId;")
    lines.append("    const char *name;")
    lines.append("};")
    lines.append("")
    lines.append("static const TitleNameEntry kTitleNames[] =")
    lines.append("{")
    for tid in sorted(titles):
        lines.append("    { 0x%08X, %s }," % (tid, c_string(titles[tid])))
    lines.append("};")
    lines.append("")
    lines.append("// The name for titleId, or NULL if it isn't in the list.")
    lines.append("static const char *LookupTitleName(unsigned long titleId)")
    lines.append("{")
    lines.append("    int lo = 0, hi = (int)(sizeof(kTitleNames) / sizeof(kTitleNames[0])) - 1;")
    lines.append("    while (lo <= hi)")
    lines.append("    {")
    lines.append("        int mid = (lo + hi) / 2;")
    lines.append("        if (kTitleNames[mid].titleId == titleId)")
    lines.append("            return kTitleNames[mid].name;")
    lines.append("        if (kTitleNames[mid].titleId < titleId)")
    lines.append("            lo = mid + 1;")
    lines.append("        else")
    lines.append("            hi = mid - 1;")
    lines.append("    }")
    lines.append("    return 0;")
    lines.append("}")
    lines.append("")
    lines.append("#endif")
    lines.append("")

    with open(OUT_HEADER, "w", newline="\r\n", encoding="ascii") as f:
        f.write("\n".join(lines))
    print("%d titles -> %s" % (len(titles), os.path.relpath(OUT_HEADER, ROOT)))


if __name__ == "__main__":
    main()
