"""Generates BoxArtBanner.h: the box art banners compiled into the XEX.

The banner down the left of every box art tile - for a disc game,
Media/BoxArtBanner.png: green at the top, "XBOX 360" reading upwards, the
logo at the foot. It replaces the header strip each cover's own case insert
carries, which changed design over the console's life, so every tile matches
whichever era its case came from. An Xbox Live Arcade game's tile has its own,
Media/BoxArtBannerXbla.png, and an indie game's Media/BoxArtBannerXblig.png;
until there's one, those get the disc banner too.

Each is 94 x 512: in the 512 x 512 tile, the banner takes the left 94 pixels
and the front of the case the other 418 (CoverArt.h's COVER_BANNER_W and
COVER_FRONT_W). The PNGs are stored as they are and decoded by PngDecode.cpp
on the cover worker, the same way the button atlas is.

Run from the repo root:  python tools/make_box_banner.py
"""

import os
import struct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA = os.path.join(ROOT, 'Media')
OUTPUT = os.path.join(ROOT, 'src', 'BoxArtBanner.h')

EXPECTED = (94, 512)

# (file in Media, the array's name, required)
BANNERS = [
    ('BoxArtBanner.png', 'kBoxArtBannerPng', True),
    ('BoxArtBannerXbla.png', 'kBoxArtBannerXblaPng', False),
    ('BoxArtBannerXblig.png', 'kBoxArtBannerXbligPng', False),
]


def read_banner(name, required):
    path = os.path.join(MEDIA, name)
    if not os.path.exists(path):
        if required:
            raise SystemExit('%s is missing' % path)
        return None
    png = open(path, 'rb').read()
    if png[:8] != b'\x89PNG\r\n\x1a\n':
        raise SystemExit('%s is not a PNG' % path)
    width, height = struct.unpack('>II', png[16:24])
    if (width, height) != EXPECTED:
        raise SystemExit('%s is %dx%d; it has to be %dx%d' % ((path, width, height) + EXPECTED))
    return png


def array_lines(symbol, png):
    if png is None:
        # Not there yet: an empty one, which CoverArt.cpp takes as "use the
        # disc banner".
        return ['static const unsigned long %sSize = 0;' % symbol,
                'static const unsigned char %s[1] = { 0 };' % symbol, '']
    lines = ['static const unsigned long %sSize = %d;' % (symbol, len(png)),
             'static const unsigned char %s[%d] =' % (symbol, len(png)),
             '{']
    for i in range(0, len(png), 16):
        lines.append('    ' + ', '.join('0x%02X' % b for b in png[i:i + 16]) + ',')
    lines += ['};', '']
    return lines


lines = [
    '// GENERATED by tools/make_box_banner.py - do not edit by hand; edit',
    '// Media/BoxArtBanner.png or Media/BoxArtBannerXbla.png and re-run the script.',
    '//',
    '// The banners down the left of the box art tiles, as PNG bytes: a disc',
    "// game's, and an Xbox Live Arcade game's - empty while there isn't one.",
    '',
    '#ifndef BOX_ART_BANNER_H',
    '#define BOX_ART_BANNER_H',
    '',
    '#define BOX_ART_BANNER_WIDTH  %d' % EXPECTED[0],
    '#define BOX_ART_BANNER_HEIGHT %d' % EXPECTED[1],
    '',
]
for name, symbol, required in BANNERS:
    png = read_banner(name, required)
    lines += array_lines(symbol, png)
    print('%s: %s' % (name, '%d bytes of PNG' % len(png) if png is not None else 'not there - left empty'))
lines += ['#endif', '']

open(OUTPUT, 'w', newline='\r\n').write('\n'.join(lines))
print('wrote %s' % OUTPUT)
