"""
Signs a release's XEX, so the app's updater will install it.

    python tools/sign_release.py --new-key          once, ever
    python tools/sign_release.py Release/Omni360.xex   for each release

Omni360 updates itself from GitHub's releases, and only installs an XEX whose
signature checks out against the public key compiled into it (UpdateKey.h).
So a release needs Omni360.xex.sig beside Omni360.xex - this writes it - and
someone who got into the GitHub account still couldn't push a build to
anyone's console without the private key, which never leaves this PC.

The key is ECDSA on P-256, made and used with openssl (Git for Windows has
one); the signature is over the XEX's SHA-256, DER-encoded, which is what
BearSSL's br_ecdsa_i31_vrfy_asn1 checks on the console.

    --new-key   Makes the private key - by default in your user folder,
                %USERPROFILE%\\.omni360\\release-signing-key.pem, well away from
                the repository - and writes its public half into UpdateKey.h.
                Refuses if the key already exists. BACK THE KEY UP: lose it,
                and builds signed with a new one won't install over ones that
                trust the old - everyone would have to update by hand once.
    --key PATH  Another key file.

Signing checks the XEX looks like one, signs it, checks the signature with
the public key in UpdateKey.h - so a key that doesn't match the app's is
caught here, not on someone's console - and prints the XEX's SHA-256 for the
release notes.
"""
import argparse, hashlib, os, re, shutil, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEY_HEADER = os.path.join(ROOT, "src", "UpdateKey.h")
DEFAULT_KEY = os.path.join(os.path.expanduser("~"), ".omni360", "release-signing-key.pem")


def find_openssl():
    found = shutil.which("openssl")
    if found:
        return found
    for guess in (r"C:\Program Files\Git\usr\bin\openssl.exe", r"C:\Program Files\Git\mingw64\bin\openssl.exe"):
        if os.path.exists(guess):
            return guess
    sys.exit("openssl wasn't found - install Git for Windows, or put openssl on the PATH")


def openssl(*args, data=None):
    result = subprocess.run([find_openssl()] + list(args), input=data, capture_output=True)
    if result.returncode != 0:
        sys.exit("openssl %s failed:\n%s" % (args[0], result.stderr.decode(errors="replace")))
    return result.stdout


def public_point(key_path):
    """The key's public point, uncompressed: 04 || X || Y, 65 bytes."""
    der = openssl("ec", "-in", key_path, "-pubout", "-outform", "DER")
    point = der[-65:]
    if len(point) != 65 or point[0] != 0x04:
        sys.exit("that isn't a P-256 key")
    return point


def header_point():
    """The public point compiled into the app, from UpdateKey.h."""
    if not os.path.exists(KEY_HEADER):
        sys.exit("UpdateKey.h is missing - make a key with --new-key first")
    text = open(KEY_HEADER, encoding="utf-8").read()
    body = text[text.index("kUpdatePublicKey"):]
    body = body[body.index("{") + 1:body.index("}")]
    return bytes(int(h, 16) for h in re.findall(r"0x([0-9A-Fa-f]{2})", body))


def write_header(point, key_path):
    rows = []
    for i in range(0, len(point), 13):
        rows.append("    " + ", ".join("0x%02X" % b for b in point[i:i + 13]) + ",")
    fingerprint = hashlib.sha256(point).hexdigest()
    text = "\n".join([
        "// GENERATED by tools/sign_release.py --new-key - do not edit by hand.",
        "//",
        "// The public half of the key Omni360's releases are signed with. The",
        "// updater installs an XEX only if its .sig verifies against this: ECDSA",
        "// on P-256 over the XEX's SHA-256. The private half stays on the PC that",
        "// signs releases, never in this repository.",
        "//",
        "// Key fingerprint (SHA-256 of the point): %s" % fingerprint,
        "",
        "#ifndef UPDATE_KEY_H",
        "#define UPDATE_KEY_H",
        "",
        "// Uncompressed: 0x04, then X, then Y.",
        "static const unsigned char kUpdatePublicKey[65] =",
        "{",
    ] + rows + [
        "};",
        "",
        "#endif",
        "",
    ])
    open(KEY_HEADER, "w", encoding="utf-8", newline="\n").write(text)
    return fingerprint


def new_key(key_path):
    if os.path.exists(key_path):
        sys.exit("%s already exists - not replacing it. Releases signed with it would\n"
                 "stop installing over builds that trust it." % key_path)
    os.makedirs(os.path.dirname(key_path), exist_ok=True)
    openssl("ecparam", "-name", "prime256v1", "-genkey", "-noout", "-out", key_path)
    fingerprint = write_header(public_point(key_path), key_path)
    print("made %s" % key_path)
    print("wrote %s (key fingerprint %s)" % (KEY_HEADER, fingerprint))
    print()
    print("Back the key file up somewhere safe and private - a password manager, or an")
    print("encrypted USB stick. Never commit it, and never put it in a release.")


def sign(xex_path, key_path):
    if not os.path.exists(key_path):
        sys.exit("no key at %s - make one with --new-key, or pass --key" % key_path)
    data = open(xex_path, "rb").read()
    if data[:4] != b"XEX2":
        sys.exit("%s doesn't start with XEX2 - is it an Xbox 360 executable?" % xex_path)

    point = public_point(key_path)
    if point != header_point():
        sys.exit("this key isn't the one in UpdateKey.h - the app would refuse what it signs")

    sig_path = xex_path + ".sig"
    openssl("dgst", "-sha256", "-sign", key_path, "-out", sig_path, xex_path)

    # Checked as the console will check it: against the public key alone.
    with tempfile.TemporaryDirectory() as tmp:
        pub = os.path.join(tmp, "pub.pem")
        open(pub, "wb").write(openssl("ec", "-in", key_path, "-pubout"))
        result = subprocess.run([find_openssl(), "dgst", "-sha256", "-verify", pub, "-signature", sig_path, xex_path],
                                capture_output=True)
        if result.returncode != 0:
            os.remove(sig_path)
            sys.exit("the signature didn't verify - not written")

    print("signed %s" % xex_path)
    print("wrote  %s (%d bytes)" % (sig_path, os.path.getsize(sig_path)))
    print("SHA-256 %s" % hashlib.sha256(data).hexdigest())
    print()
    print("Attach both files to the release on GitHub.")


def main():
    parser = argparse.ArgumentParser(description="Sign an Omni360 release so its updater will install it.")
    parser.add_argument("xex", nargs="?", help="the XEX to sign, e.g. Release/Omni360.xex")
    parser.add_argument("--new-key", action="store_true", help="make the signing key, once")
    parser.add_argument("--key", default=DEFAULT_KEY, help="the private key (default: %(default)s)")
    args = parser.parse_args()

    if args.new_key:
        new_key(args.key)
    elif args.xex:
        sign(args.xex, args.key)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
