/*
FILE : CoverArt.cpp
PROJECT : Omni360
DESCRIPTION : Box art from Xbox Live, else xboxunity.net, looked up, cut to a tile and
              cached on a worker thread. See CoverArt.h.
*/

#include "CoverArt.h"
#include "downloadFile.h"
#include "HttpPlain.h"
#include "OutputConsole.h"
#include "cJSON.h"
#include "ImageDecode.h"
#include "PngDecode.h"
#include "BoxArtBanner.h" // generated by tools/make_box_banner.py
#include "StoreCatalog.h" // XblaGameByTitleId

#include <xtl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

#define COVER_DIR          "game:\\Covers"
#define COVER_INFO_URL     "https://xboxunity.net/Resources/Lib/CoverInfo.php?titleid=%08lX"
#define COVER_IMAGE_URL    "https://xboxunity.net/Resources/Lib/Cover.php?size=large&cid=%s"
#define BOXART_URL         "http://download.xbox.com/content/images/66acd000-77fe-1000-9115-d802%08lx/1033/boxartlg.jpg"

// The marker for a game neither source has a cover for. Renamed from "none",
// which meant only that xboxunity had none - those are asked about again, as
// Xbox Live may have one.
#define NONE_EXTENSION     "none2"

// The cache file: a small header, then the front of the case as pixels.
// Older files read as unusable and are fetched again, once: "OMC1" held the
// whole square with the cover's own header strip, and "OMC2" fronts were cut
// close enough to the spine to keep a sliver of it on some covers.
#define COVER_FILE_MAGIC   0x4F4D4333 // "OMC3"
#define COVER_PIXEL_BYTES  ((unsigned long)COVER_FRONT_W * COVER_SIZE * 4)

// How long "no cover anywhere for this" is believed before asking again.
#define NONE_RETRY_DAYS    7

// Generous: the covers seen are about 530KB, and the listing a few KB.
#define INFO_BUFFER_BYTES  (64 * 1024)
#define IMAGE_BUFFER_BYTES (2 * 1024 * 1024)
#define BOXART_BUFFER_BYTES (512 * 1024) // Xbox Live's box art is about 60KB

#define MAX_REQUESTED      256
#define MAX_READY          4  // a library tile is 1MB - don't run far ahead of the UI

// A cover's steps are timed, and logged when the whole takes this long.
#define TIMING_LOG_MS      4.0

struct CoverFileHeader
{
    unsigned long magic;
    unsigned long width;
    unsigned long height;
    unsigned long reserved;
};

static CRITICAL_SECTION g_lock;
static HANDLE g_wake = NULL;
static HANDLE g_thread = NULL;
static bool g_running = false;
static bool g_shutdown = false;

// What's asked for, and how far through it the worker is.
static unsigned long g_requested[MAX_REQUESTED];
static int g_requestedCount = 0;
static int g_nextRequest = 0;

// Handed over already, this session - not asked for again if the library is
// rescanned.
static unsigned long g_delivered[MAX_REQUESTED];
static int g_deliveredCount = 0;

// The Store's tiles on screen, served first.
#define MAX_STORE_REQUESTED 64
static unsigned long g_storeRequested[MAX_STORE_REQUESTED];
static int g_storeRequestedCount = 0;
static int g_nextStoreRequest = 0;

static CoverData g_ready[MAX_READY];
static int g_readyCount = 0;

// ---------------------------------------------------------------------------
// The cache on disk
// ---------------------------------------------------------------------------

static void CoverPath(unsigned long titleId, const char *extension, char *out, size_t outSize)
{
    _snprintf(out, outSize, COVER_DIR "\\%08lX.%s", titleId, extension);
    out[outSize - 1] = '\0';
}

// The cached front, or NULL.
static unsigned char *ReadCachedCover(unsigned long titleId)
{
    char path[64];
    CoverPath(titleId, "bin", path, sizeof(path));

    FILE *f = fopen(path, "rb");
    if (f == NULL)
        return NULL;

    CoverFileHeader header;
    unsigned char *pixels = NULL;

    if (fread(&header, sizeof(header), 1, f) == 1 && header.magic == COVER_FILE_MAGIC &&
        header.width == COVER_FRONT_W && header.height == COVER_SIZE)
    {
        pixels = (unsigned char *)malloc(COVER_PIXEL_BYTES);
        if (pixels != NULL && fread(pixels, 1, COVER_PIXEL_BYTES, f) != COVER_PIXEL_BYTES)
        {
            free(pixels);
            pixels = NULL;
        }
    }
    fclose(f);

    if (pixels == NULL)
    {
        // Truncated or from some other version - fetched afresh instead.
        dprintf("[covers] %s is unreadable, fetching the cover again\n", path);
        DeleteFileA(path);
    }
    return pixels;
}

// True while a "none" marker is younger than NONE_RETRY_DAYS.
static bool RecentlyMissing(unsigned long titleId)
{
    char path[64];
    CoverPath(titleId, NONE_EXTENSION, path, sizeof(path));

    WIN32_FILE_ATTRIBUTE_DATA attrs;
    if (!GetFileAttributesExA(path, GetFileExInfoStandard, &attrs))
        return false;

    FILETIME nowFt;
    GetSystemTimeAsFileTime(&nowFt);

    ULARGE_INTEGER now, written;
    now.LowPart = nowFt.dwLowDateTime;
    now.HighPart = nowFt.dwHighDateTime;
    written.LowPart = attrs.ftLastWriteTime.dwLowDateTime;
    written.HighPart = attrs.ftLastWriteTime.dwHighDateTime;

    const unsigned long long retryAfter = (unsigned long long)NONE_RETRY_DAYS * 24 * 60 * 60 * 10000000ULL;
    return now.QuadPart < written.QuadPart + retryAfter;
}

static void WriteCoverFile(unsigned long titleId, const unsigned long *pixels)
{
    CreateDirectoryA(COVER_DIR, NULL); // fails harmlessly once it exists

    char path[64], noneMarker[64], oldMarker[64];
    CoverPath(titleId, pixels != NULL ? "bin" : NONE_EXTENSION, path, sizeof(path));
    CoverPath(titleId, NONE_EXTENSION, noneMarker, sizeof(noneMarker));
    CoverPath(titleId, "none", oldMarker, sizeof(oldMarker));
    DeleteFileA(oldMarker); // superseded either way

    FILE *f = fopen(path, "wb");
    if (f == NULL)
    {
        dprintf("[covers] couldn't write %s\n", path);
        return;
    }

    bool ok = true;
    if (pixels != NULL)
    {
        CoverFileHeader header = {COVER_FILE_MAGIC, COVER_FRONT_W, COVER_SIZE, 0};
        ok = fwrite(&header, sizeof(header), 1, f) == 1 &&
             fwrite(pixels, 1, COVER_PIXEL_BYTES, f) == COVER_PIXEL_BYTES;
    }
    fclose(f);

    if (!ok)
    {
        dprintf("[covers] writing %s failed - removed\n", path);
        DeleteFileA(path);
    }
    else if (pixels != NULL)
    {
        DeleteFileA(noneMarker); // it has a cover now
    }
}

// ---------------------------------------------------------------------------
// xboxunity
// ---------------------------------------------------------------------------

// The HTTP client's chatter, failures only: browsing the Store fetches covers
// by the dozen, and a few lines for each slowed it and buried the rest.
static void QuietPrint(const char *format, ...)
{
    char line[1024];
    va_list args;
    va_start(args, format);
    _vsnprintf(line, sizeof(line), format, args);
    va_end(args);
    line[sizeof(line) - 1] = '\0';

    if (strstr(line, "ERROR") != NULL || strstr(line, "Failed") != NULL || strstr(line, "failed") != NULL)
        dprintf("%s", line);
}

// A downloaded image, malloc'd.
struct Download
{
    unsigned char *bytes;
    unsigned long size;
};

enum FetchResult
{
    FETCH_OK,
    FETCH_NO_COVER,   // xboxunity and Xbox Live answered, and have nothing for this game
    FETCH_FAILED      // couldn't ask - the network, or an error; tried again next launch
};

// The CoverID to download: the first official cover, else the first listed.
static bool ChooseCoverId(const char *json, unsigned long long jsonLen, char *outId, size_t outSize)
{
    cJSON *root = cJSON_ParseWithLength(json, (size_t)jsonLen);
    if (root == NULL)
        return false;

    const char *chosen = NULL;
    const cJSON *covers = cJSON_GetObjectItemCaseSensitive(root, "Covers");

    for (int pass = 0; pass < 2 && chosen == NULL; ++pass)
    {
        const cJSON *cover = NULL;
        cJSON_ArrayForEach(cover, covers)
        {
            const cJSON *id = cJSON_GetObjectItemCaseSensitive(cover, "CoverID");
            const cJSON *official = cJSON_GetObjectItemCaseSensitive(cover, "Official");
            if (!cJSON_IsString(id) || id->valuestring == NULL || id->valuestring[0] == '\0')
                continue;

            bool isOfficial = cJSON_IsString(official) && official->valuestring != NULL &&
                              strcmp(official->valuestring, "1") == 0;
            if (pass == 0 && !isOfficial)
                continue;

            chosen = id->valuestring;
            break;
        }
    }

    bool found = false;
    if (chosen != NULL && strlen(chosen) < outSize)
    {
        // Only digits go into the next URL.
        found = true;
        for (const char *c = chosen; *c != '\0'; ++c)
        {
            if (*c < '0' || *c > '9')
                found = false;
        }
        if (found)
            strcpy(outId, chosen);
    }

    cJSON_Delete(root);
    return found;
}

// Xbox Live's box art, the first choice: the front alone, cut below under its
// header strip. A 219x300 JPEG of about 60KB, over plain HTTP, against
// xboxunity's 900x600 insert of about 530KB over HTTPS - a fraction of the
// work to decode, and at the size tiles are drawn near enough as sharp.
static FetchResult FetchBoxArt(unsigned long titleId, Download *out)
{
    char url[160];
    _snprintf(url, sizeof(url), BOXART_URL, titleId);
    url[sizeof(url) - 1] = '\0';

    char *image = (char *)malloc(BOXART_BUFFER_BYTES + 1);
    if (image == NULL)
        return FETCH_FAILED;

    unsigned long long imageLen = 0;
    const int status = HttpGetPlain(url, NULL, image, BOXART_BUFFER_BYTES, &imageLen);
    if (status == 404)
    {
        free(image);
        return FETCH_NO_COVER; // xboxunity is asked next
    }
    if (status != 200 || imageLen < 64)
    {
        dprintf("[covers] %08lX: Xbox Live box art -> HTTP %d, %I64u bytes\n", titleId, status, imageLen);
        free(image);
        return FETCH_FAILED;
    }

    out->bytes = (unsigned char *)image;
    out->size = (unsigned long)imageLen;
    return FETCH_OK;
}

// xboxunity's cover, for a game Xbox Live has no box art for - a Japan-only
// disc, say: the whole case insert, cut to its front below.
static FetchResult FetchXboxUnityCover(unsigned long titleId, Download *out)
{
    char url[256];
    _snprintf(url, sizeof(url), COVER_INFO_URL, titleId);
    url[sizeof(url) - 1] = '\0';

    char *info = (char *)malloc(INFO_BUFFER_BYTES + 1);
    if (info == NULL)
        return FETCH_FAILED;

    unsigned long long infoLen = INFO_BUFFER_BYTES;
    int status = httpRequestHTTPS(url, HTTP_GET, NULL, NULL, "", info, &infoLen, false, NULL, 0, QuietPrint);
    if (status != 200)
    {
        dprintf("[covers] %08lX: cover list -> HTTP %d\n", titleId, status);
        free(info);
        return FETCH_FAILED;
    }
    info[infoLen] = '\0';

    char coverId[32];
    bool haveCover = ChooseCoverId(info, infoLen, coverId, sizeof(coverId));
    free(info);

    if (!haveCover)
        return FETCH_NO_COVER;

    _snprintf(url, sizeof(url), COVER_IMAGE_URL, coverId);
    url[sizeof(url) - 1] = '\0';

    char *image = (char *)malloc(IMAGE_BUFFER_BYTES);
    if (image == NULL)
        return FETCH_FAILED;

    unsigned long long imageLen = IMAGE_BUFFER_BYTES;
    status = httpRequestHTTPS(url, HTTP_GET, NULL, NULL, "", image, &imageLen, false, NULL, 0, QuietPrint);
    if (status != 200 || imageLen < 64)
    {
        dprintf("[covers] %08lX: cover %s -> HTTP %d, %I64u bytes\n", titleId, coverId, status, imageLen);
        free(image);
        return FETCH_FAILED;
    }

    out->bytes = (unsigned char *)image;
    out->size = (unsigned long)imageLen;
    return FETCH_OK;
}

// Xbox Live's box art, else xboxunity's. No cover only when both answered
// and had none; a failure to ask either is tried again another time.
static FetchResult FetchCover(unsigned long titleId, Download *out)
{
    const FetchResult xboxLive = FetchBoxArt(titleId, out);
    if (xboxLive == FETCH_OK)
        return FETCH_OK;

    const FetchResult xboxUnity = FetchXboxUnityCover(titleId, out);
    if (xboxUnity == FETCH_OK)
        return FETCH_OK;
    if (xboxLive == FETCH_FAILED || xboxUnity == FETCH_FAILED)
        return FETCH_FAILED;

    dprintf("[covers] %08lX: no cover on Xbox Live or xboxunity\n", titleId);
    return FETCH_NO_COVER;
}

// ---------------------------------------------------------------------------
// The tile: the front of the case cut from the download, the banner beside it
// ---------------------------------------------------------------------------

// Where the front of the case sits in xboxunity's case inserts, as fractions
// of the image, on their 900x600 covers. The header strip above it is the top
// 76 rows. The spine's width varies by a few pixels from scan to scan - the
// front starts anywhere from about x = 469 (Red Dead Redemption) to 478
// (Halo 4) - so the cut starts at 481, clear of the widest, rather than
// leaving a sliver of spine down the left of some covers.
#define INSERT_FRONT_X   (481.0f / 900.0f)
#define INSERT_HEADER_H  (76.0f / 600.0f)

// Xbox Live's box art: the front alone, 219x300, under a header strip that
// ends in a green line at row 37 (Halo 3's, Forza Horizon 2's, BioShock's
// alike).
#define BOXART_HEADER_H  (38.0f / 300.0f)

// The banner's colour, for tiles if the banner itself won't decode.
#define BANNER_GREEN     0xFF107C10

// The front of the case, under its header strip, scaled to COVER_FRONT_W x
// COVER_SIZE - the part of the tile beside the banner. malloc'd.
//
// An image that is neither a whole insert (about 3:2) nor Xbox Live's box art
// (about 0.73:1) can't be cut that way; it gets the middle of itself at the
// front's proportions instead.
static unsigned long *CutCoverFront(const unsigned long *image, int w, int h)
{
    const int FW = COVER_FRONT_W, FH = COVER_SIZE;
    unsigned long *pixels = (unsigned long *)malloc((size_t)FW * FH * 4);
    if (pixels == NULL)
        return NULL;

    const float aspect = (float)w / (float)h;
    const bool wholeInsert = (aspect > 1.35f && aspect < 1.65f);
    const bool boxArt = (aspect > 0.70f && aspect < 0.76f);

    float srcX, srcY, srcW, srcH;
    if (boxArt)
    {
        // Everything under the header, a few columns off the sides to keep
        // the front's proportions: 214 of 219 wide.
        srcY = BOXART_HEADER_H * (float)h;
        srcH = (float)h - srcY;
        srcW = srcH * (float)FW / (float)FH;
        if (srcW > (float)w)
            srcW = (float)w;
        srcX = ((float)w - srcW) * 0.5f;
    }
    else if (wholeInsert)
    {
        srcX = INSERT_FRONT_X * (float)w;
        srcY = INSERT_HEADER_H * (float)h;
        srcW = (float)w - srcX;
        srcH = (float)h - srcY;

        // Narrower than it was cut for, so take a few rows off to keep its
        // proportions - a little more off the top, which also clears the
        // header strip's bottom edge.
        float wantH = srcW * (float)FH / (float)FW;
        if (wantH < srcH)
        {
            float trim = srcH - wantH;
            srcY += trim * 0.55f;
            srcH = wantH;
        }
    }
    else
    {
        const float want = (float)FW / (float)FH;
        srcW = (float)w;
        srcH = (float)h;
        if (aspect > want) srcW = (float)h * want;
        else srcH = (float)w / want;
        srcX = ((float)w - srcW) * 0.5f;
        srcY = ((float)h - srcH) * 0.5f;
    }

    if (!ScaleArgb(image, w, h, srcX, srcY, srcW, srcH, FW, FH, pixels))
    {
        free(pixels);
        return NULL;
    }
    return pixels;
}

// Whether a game's tile gets the arcade banner: an Xbox Live Arcade game's
// title ID starts 5841 - "XA" - and no disc game's does, which catches arcade
// games in the library the Store hasn't got. The few arcade games with other
// IDs are known by the Store's list.
static bool IsArcadeTitle(unsigned long titleId)
{
    return (titleId >> 16) == 0x5841 || XblaGameByTitleId(titleId) != NULL;
}

// The banners, each decoded from BoxArtBanner.h the first time a tile needs
// it: a disc game's [BANNER_DISC], an arcade game's and an Original Xbox
// game's. NULL if one wouldn't decode - or while there isn't one - and a
// tile then gets the disc banner, or failing that a plain green strip. Only
// the worker uses them, and StopCoverArt lets them go once the worker's
// stopped.
#define BANNER_DISC   0
#define BANNER_ARCADE 1
#define BANNER_XBOX   2
#define BANNER_COUNT  3
static unsigned long *g_bannerPixels[BANNER_COUNT] = { NULL, NULL, NULL };
static bool g_bannerTried[BANNER_COUNT] = { false, false, false };

static const unsigned long *DecodeBanner(int which)
{
    if (g_bannerTried[which])
        return g_bannerPixels[which];
    g_bannerTried[which] = true;

    const unsigned char *png = (which == BANNER_XBOX) ? kBoxArtBannerXboPng
                             : (which == BANNER_ARCADE) ? kBoxArtBannerXblaPng : kBoxArtBannerPng;
    const unsigned long size = (which == BANNER_XBOX) ? kBoxArtBannerXboPngSize
                             : (which == BANNER_ARCADE) ? kBoxArtBannerXblaPngSize : kBoxArtBannerPngSize;
    const char *name = (which == BANNER_XBOX) ? "Original Xbox banner"
                     : (which == BANNER_ARCADE) ? "arcade banner" : "banner";
    if (size == 0)
        return NULL;

    unsigned long w = 0, h = 0;
    const char *error = NULL;
    unsigned long *pixels = NULL;
    if (!PngDecodeToArgb(png, size, &pixels, &w, &h, &error))
    {
        dprintf("[covers] the %s would not decode: %s\n", name, error != NULL ? error : "?");
        return NULL;
    }
    if (w != COVER_BANNER_W || h != COVER_SIZE)
    {
        dprintf("[covers] the %s is %lux%lu, not %dx%d\n", name, w, h, COVER_BANNER_W, COVER_SIZE);
        PngFree(pixels);
        return NULL;
    }

    g_bannerPixels[which] = pixels;
    return pixels;
}

static const unsigned long *Banner(int which)
{
    const unsigned long *banner = (which != BANNER_DISC) ? DecodeBanner(which) : NULL;
    return banner != NULL ? banner : DecodeBanner(BANNER_DISC);
}

// Which banner a game's tile gets.
static int BannerFor(unsigned long titleId)
{
    if (IsArcadeTitle(titleId))
        return BANNER_ARCADE;
    if (IsXboxTitleId(titleId))
        return BANNER_XBOX;
    return BANNER_DISC;
}

static void ReleaseBanners()
{
    for (int i = 0; i < BANNER_COUNT; ++i)
    {
        if (g_bannerPixels[i] != NULL)
            PngFree(g_bannerPixels[i]);
        g_bannerPixels[i] = NULL;
        g_bannerTried[i] = false;
    }
}

// The tile's square: the banner - the arcade's or the Original Xbox's, for
// one of those - then the front beside it. malloc'd.
static unsigned long *ComposeTile(const unsigned long *front, int banner)
{
    const int N = COVER_SIZE;
    unsigned long *square = (unsigned long *)malloc((size_t)N * N * 4);
    if (square == NULL)
        return NULL;

    const unsigned long *bannerPixels = Banner(banner);

    for (int y = 0; y < N; ++y)
    {
        unsigned long *row = square + y * N;
        if (bannerPixels != NULL)
            memcpy(row, bannerPixels + y * COVER_BANNER_W, COVER_BANNER_W * 4);
        else
            for (int x = 0; x < COVER_BANNER_W; ++x)
                row[x] = BANNER_GREEN;
        memcpy(row + COVER_BANNER_W, front + y * COVER_FRONT_W, COVER_FRONT_W * 4);
    }
    return square;
}

// ---------------------------------------------------------------------------
// The worker
// ---------------------------------------------------------------------------

static bool AlreadyDelivered(unsigned long titleId)
{
    for (int i = 0; i < g_deliveredCount; ++i)
    {
        if (g_delivered[i] == titleId)
            return true;
    }
    return false;
}

// Under the lock.
static void Deliver(const CoverData &data)
{
    g_ready[g_readyCount++] = data;
    if (g_deliveredCount < MAX_REQUESTED)
        g_delivered[g_deliveredCount++] = data.titleId;
}

static DWORD WINAPI CoverEntry(LPVOID)
{
    for (;;)
    {
        EnterCriticalSection(&g_lock);

        if (g_shutdown)
        {
            LeaveCriticalSection(&g_lock);
            break;
        }

        // Nothing to do, or the UI hasn't caught up: wait to be woken.
        const bool storeWaiting = (g_nextStoreRequest < g_storeRequestedCount);
        if ((!storeWaiting && g_nextRequest >= g_requestedCount) || g_readyCount >= MAX_READY)
        {
            LeaveCriticalSection(&g_lock);
            WaitForSingleObject(g_wake, INFINITE);
            continue;
        }

        // The Store's first: they're on screen now.
        const bool forStore = storeWaiting;
        unsigned long titleId = forStore ? g_storeRequested[g_nextStoreRequest++] : g_requested[g_nextRequest++];
        bool skip = !forStore && AlreadyDelivered(titleId);
        LeaveCriticalSection(&g_lock);

        if (skip)
            continue;

        // The front: from the cache, else downloaded, decoded and cut.
        unsigned long *front = (unsigned long *)ReadCachedCover(titleId);
        const bool fresh = (front == NULL);
        double decodeMs = 0.0, cutMs = 0.0;
        int imageW = 0, imageH = 0;
        unsigned long downloaded = 0;
        if (fresh)
        {
            if (RecentlyMissing(titleId))
                continue;

            Download download = {NULL, 0};
            FetchResult result = FetchCover(titleId, &download);
            if (result == FETCH_NO_COVER)
                WriteCoverFile(titleId, NULL);
            if (result != FETCH_OK)
                continue;

            const double decodeStarted = ImageTimerMs();
            downloaded = download.size;
            unsigned long *image = DecodeImageToArgb(download.bytes, download.size, &imageW, &imageH);
            free(download.bytes);
            const double cutStarted = ImageTimerMs();
            decodeMs = cutStarted - decodeStarted;
            if (image == NULL || imageW < 16 || imageH < 16)
            {
                dprintf("[covers] %08lX: the download wouldn't decode (%s)\n", titleId, ImageDecodeError());
                if (image != NULL)
                    free(image);
                // Noted like a game with no cover, so it isn't downloaded
                // again on every launch.
                WriteCoverFile(titleId, NULL);
                continue;
            }
            front = CutCoverFront(image, imageW, imageH);
            free(image);
            cutMs = ImageTimerMs() - cutStarted;
            if (front == NULL)
                continue;
        }

        // The banner beside it, and the Store's halved.
        const double tileStarted = ImageTimerMs();
        unsigned long *tile = ComposeTile(front, BannerFor(titleId));
        if (tile != NULL && forStore)
        {
            unsigned long *half = HalveArgb(tile, COVER_SIZE, COVER_SIZE);
            free(tile);
            tile = half;
        }
        const double tileMs = ImageTimerMs() - tileStarted;
        if (tile == NULL)
        {
            free(front);
            continue;
        }

        if (decodeMs + cutMs + tileMs >= TIMING_LOG_MS)
        {
            if (fresh)
                dprintf("[timing] cover %08lX (%dx%d, %lu KB, %s, worker): decode %.1f + cut %.1f + tile %.1f = %.1f ms\n",
                        titleId, imageW, imageH, downloaded / 1024, forStore ? "Store" : "library", decodeMs, cutMs,
                        tileMs, decodeMs + cutMs + tileMs);
            else
                dprintf("[timing] cover %08lX (cached, %s, worker): tile %.1f ms\n", titleId,
                        forStore ? "Store" : "library", tileMs);
        }

        CoverData data;
        data.titleId = titleId;
        data.pixels = tile;
        data.side = forStore ? COVER_STORE_SIZE : COVER_SIZE;
        data.forStore = forStore;
        EnterCriticalSection(&g_lock);
        if (forStore)
            g_ready[g_readyCount++] = data; // not marked delivered: the Store may ask again
        else
            Deliver(data);
        LeaveCriticalSection(&g_lock);

        // Cached after it's handed over, so the tile isn't kept waiting on
        // the disk.
        if (fresh)
            WriteCoverFile(titleId, front);
        free(front);
    }

    return 0;
}

bool StartCoverArt()
{
    if (g_running)
        return true;

    InitializeCriticalSection(&g_lock);

    g_wake = CreateEvent(NULL, FALSE, FALSE, NULL); // auto-reset
    if (g_wake == NULL)
    {
        dprintf("[covers] CreateEvent failed (%lu)\n", GetLastError());
        return false;
    }

    // The same stack as the other workers, for the same HTTP and TLS buffers.
    g_thread = CreateThread(NULL, 256 * 1024, CoverEntry, NULL, CREATE_SUSPENDED, NULL);
    if (g_thread == NULL)
    {
        dprintf("[covers] CreateThread failed (%lu)\n", GetLastError());
        CloseHandle(g_wake);
        g_wake = NULL;
        return false;
    }

#ifdef _XBOX
    // Hardware thread 5, core 2's second - the download worker's core, but
    // a cover is a moment of TLS and a few tens of milliseconds of decoding
    // between long waits on the network, so the two hardly meet. The search
    // worker has core 1 to itself for matching.
    XSetThreadProcessor(g_thread, 5);
#endif

    g_running = true;
    ResumeThread(g_thread);

    dprintf("[covers] cover worker started\n");
    return true;
}

bool StopCoverArt(DWORD timeoutMs)
{
    if (!g_running)
        return true;

    EnterCriticalSection(&g_lock);
    g_shutdown = true;
    LeaveCriticalSection(&g_lock);
    SetEvent(g_wake);

    bool stopped = (WaitForSingleObject(g_thread, timeoutMs) == WAIT_OBJECT_0);
    if (!stopped)
    {
        dprintf("[covers] still running after %lums - leaving anyway\n", timeoutMs);
        return false;
    }

    CloseHandle(g_thread);
    g_thread = NULL;
    g_running = false;

    // Anything never collected.
    for (int i = 0; i < g_readyCount; ++i)
        free(g_ready[i].pixels);
    g_readyCount = 0;
    ReleaseBanners();

    return true;
}

void RequestCoverArt(const unsigned long *titleIds, int count)
{
    if (!g_running)
        return;

    if (count > MAX_REQUESTED)
        count = MAX_REQUESTED;

    EnterCriticalSection(&g_lock);
    for (int i = 0; i < count; ++i)
        g_requested[i] = titleIds[i];
    g_requestedCount = count;
    g_nextRequest = 0;
    LeaveCriticalSection(&g_lock);

    SetEvent(g_wake);
}

void RequestStoreCoverArt(const unsigned long *titleIds, int count)
{
    if (!g_running)
        return;

    if (count > MAX_STORE_REQUESTED)
        count = MAX_STORE_REQUESTED;

    EnterCriticalSection(&g_lock);
    for (int i = 0; i < count; ++i)
        g_storeRequested[i] = titleIds[i];
    g_storeRequestedCount = count;
    g_nextStoreRequest = 0;
    LeaveCriticalSection(&g_lock);

    SetEvent(g_wake);
}

bool TakeCoverData(CoverData *out)
{
    if (!g_running || out == NULL)
        return false;

    bool took = false;

    EnterCriticalSection(&g_lock);
    if (g_readyCount > 0)
    {
        *out = g_ready[0];
        for (int i = 1; i < g_readyCount; ++i)
            g_ready[i - 1] = g_ready[i];
        g_readyCount--;
        took = true;
    }
    LeaveCriticalSection(&g_lock);

    if (took)
        SetEvent(g_wake); // room for the next one
    return took;
}
