// GENERATED by tools/make_store_rows.py - do not edit by hand.
//
// The Store front page's rows, under its A to Z: Popular - by how many
// people rated a game on Xbox Live - Top rated, of games with 2000 ratings or
// more, then a row for each genre with 12 games or more, the most-played
// first: a game in its main genre's, and Family's and Kinect's if tagged so.
// From the Xbox Live catalog, for 1392 of the Store's 1417 360 games.

#ifndef STORE_ROWS_H
#define STORE_ROWS_H

struct StoreRow
{
    const char *name;
    unsigned short first; // into kStoreRowGames
    unsigned char count;
};

#define STORE_ROW_COUNT 14
#define STORE_ROW_MAX_GAMES 24

#ifdef STORE_ROWS_DATA

// Title IDs, a row after another - each a game StoreGameByTitleId finds.
static const unsigned long kStoreRowGames[] =
{
    // Popular
    0x41560817, // Call of Duty: Modern Warfare 2
    0x415608CB, // Call of Duty: Modern Warfare 3
    0x41560855, // Call of Duty: Black Ops
    0x425307E6, // The Elder Scrolls V: Skyrim
    0x545408A7, // Grand Theft Auto V
    0x415608C3, // Call of Duty: Black Ops II
    0x4D53085B, // Halo: Reach
    0x45410950, // Battlefield 3
    0x4D5307E6, // Halo 3
    0x57520802, // Batman: Arkham City
    0x545407F2, // Grand Theft Auto: Episodes from Liberty City
    0x4156081C, // Call of Duty: World at War
    0x4D530919, // Halo 4
    0x415607E6, // Call of Duty 4: Modern Warfare
    0x4D5308AB, // Gears of War 3
    0x5454082B, // Red Dead Redemption
    0x454108D4, // Left 4 Dead 2
    0x534307E7, // Just Cause 2
    0x425307D5, // Fallout 3: Game of the Year Edition
    0x45410830, // Left 4 Dead
    0x4D53082D, // Gears of War 2
    0x454108A8, // Battlefield: Bad Company 2
    0x575207FD, // Mortal Kombat
    0x41560914, // Call of Duty: Advanced Warfare
    // Top rated
    0x545408A7, // Grand Theft Auto V
    0x4E4D085C, // Naruto Shippuden: Ultimate Ninja Storm 3
    0x425307D5, // Fallout 3: Game of the Year Edition
    0x415608FC, // Call of Duty: Ghosts
    0x425307D1, // The Elder Scrolls IV: Oblivion - Game of the Year Edition
    0x4D5307E8, // Mass Effect
    0x415608F8, // Destiny
    0x5454087C, // Borderlands 2
    0x454108CE, // Mass Effect 2
    0x454109BA, // Battlefield 4
    0x545408B8, // Grand Theft Auto: San Andreas
    0x555308B7, // Watch_Dogs
    0x454109D0, // Titanfall
    0x57520828, // Batman: Arkham Origins
    0x4B4D07F6, // Saints Row IV
    0x4E4D0862, // Dragon Ball Xenoverse
    0x4541099D, // Dead Space 3
    0x545408B0, // NBA 2K14
    0x555308CA, // Far Cry 4
    0x454109C1, // Madden NFL 25
    0x394F07D1, // Diablo III
    0x315A07D2, // WWE 2K16
    0x4E4D0860, // Dragon Ball Z: Battle of Z
    0x4E4D0868, // Naruto Shippuden: Ultimate Ninja Storm Revolution
    // Shooters
    0x41560817, // Call of Duty: Modern Warfare 2
    0x415608CB, // Call of Duty: Modern Warfare 3
    0x41560855, // Call of Duty: Black Ops
    0x415608C3, // Call of Duty: Black Ops II
    0x4D53085B, // Halo: Reach
    0x45410950, // Battlefield 3
    0x4D5307E6, // Halo 3
    0x4156081C, // Call of Duty: World at War
    0x4D530919, // Halo 4
    0x415607E6, // Call of Duty 4: Modern Warfare
    0x4D5308AB, // Gears of War 3
    0x5454082B, // Red Dead Redemption
    0x454108D4, // Left 4 Dead 2
    0x45410830, // Left 4 Dead
    0x4D53082D, // Gears of War 2
    0x454108A8, // Battlefield: Bad Company 2
    0x41560914, // Call of Duty: Advanced Warfare
    0x545407E7, // Borderlands
    0x415608FC, // Call of Duty: Ghosts
    0x5451086D, // Saints Row: The Third
    0x4D530877, // Halo 3: ODST
    0x4B4D07DF, // Dead Island
    0x425307E0, // Fallout: New Vegas
    0x415608F8, // Destiny
    // Action and adventure
    0x545408A7, // Grand Theft Auto V
    0x57520802, // Batman: Arkham City
    0x545407F2, // Grand Theft Auto: Episodes from Liberty City
    0x534307E7, // Just Cause 2
    0x5553085D, // Assassin's Creed: Brotherhood
    0x5553083B, // Assassin's Creed II
    0x555308AE, // Assassin's Creed III
    0x534307F6, // Batman: Arkham Asylum
    0x545107FC, // Saints Row 2
    0x55530879, // Assassin's Creed: Revelations
    0x555307D4, // Assassin's Creed
    0x434307D4, // Resident Evil 5 ~ Biohazard 5
    0x534507D6, // Sonic the Hedgehog
    0x454108DF, // Dead Space 2
    0x415607E2, // Spider-Man 3
    0x434307EC, // Dead Rising 2
    0x5454086C, // L.A. Noire
    0x425607E5, // Disney-Pixar Toy Story 3
    0x45410912, // Portal 2
    0x415608B5, // The Amazing Spider-Man
    0x45410857, // Dead Space
    0x555308C2, // Assassin's Creed IV: Black Flag
    0x545408B8, // Grand Theft Auto: San Andreas
    0x5454081A, // Bully: Scholarship Edition
    // Role-playing
    0x425307E6, // The Elder Scrolls V: Skyrim
    0x425307D5, // Fallout 3: Game of the Year Edition
    0x425307D1, // The Elder Scrolls IV: Oblivion - Game of the Year Edition
    0x4D5307E8, // Mass Effect
    0x4D5307F1, // Fable II
    0x454108CE, // Mass Effect 2
    0x454108C0, // Dragon Age: Origins
    0x4541095D, // Mass Effect 3
    0x4156082F, // Marvel: Ultimate Alliance 2
    0x535107E4, // Final Fantasy XIII
    0x4E4D083A, // Dark Souls
    0x4541090B, // Dragon Age II
    0x534507E3, // Phantasy Star Universe
    0x4541093E, // Kingdoms of Amalur: Reckoning
    0x53510806, // Final Fantasy XIII-2
    0x54510896, // Darksiders II
    0x57520824, // The Witcher 2: Assassins of Kings - Enhanced Edition
    0x4E4D07E9, // Tales of Vesperia
    0x394F07D1, // Diablo III
    0x4D5307FA, // Lost Odyssey
    0x465307E4, // Dark Souls II
    0x535107D5, // Final Fantasy XI
    0x535007D4, // Two Worlds
    0x5A4507DA, // Two Worlds II
    // Kinect
    0x425307E6, // The Elder Scrolls V: Skyrim
    0x4D530910, // Forza Motorsport 4
    0x4D5309B1, // Halo: Combat Evolved Anniversary
    0x4541095D, // Mass Effect 3
    0x5553084E, // Fighters Uncaged
    0x55530833, // Tom Clancy's Ghost Recon: Future Soldier
    0x53450846, // Rise of Nightmares
    0x45410998, // FIFA Soccer 13
    0x4541098B, // Madden NFL 13
    0x5345084D, // Sonic Free Riders
    0x4D5308B3, // Kinectimals
    0x454108F9, // Harry Potter and the Deathly Hallows: Part 1
    0x4D5308ED, // Kinect Adventures!
    0x545607D3, // Dance Central
    0x55530851, // Michael Jackson: The Experience
    0x55530850, // Motionsports: Play for Real
    0x4D5308C9, // Kinect Sports
    0x4541099D, // Dead Space 3
    0x57520801, // Game Party: In Motion
    0x54510874, // DreamWorks Kung Fu Panda 2
    0x45410961, // Need for Speed: Most Wanted - A Criterion Game
    0x43430816, // Steel Battalion: Heavy Armor
    0x4D53090E, // Kinect Star Wars
    0x4D5309D6, // Kinect Sports: Season Two
    // Fighting games
    0x575207FD, // Mortal Kombat
    0x5451085D, // WWE SmackDown vs. Raw 2011
    0x54510890, // WWE '12
    0x5553084E, // Fighters Uncaged
    0x4156084E, // Prototype
    0x54510844, // WWE SmackDown vs. Raw 2010
    0x415607DA, // Marvel: Ultimate Alliance
    0x545108B4, // WWE '13
    0x4D5707E9, // Mortal Kombat vs. DC Universe
    0x4E4D0803, // Dragon Ball: Raging Blast
    0x55530825, // Naruto: The Broken Bond
    0x4E4D0826, // Dragon Ball: Raging Blast 2
    0x43430806, // Marvel vs. Capcom 3: Fate of Two Worlds
    0x545408B2, // WWE 2K14
    0x5451082A, // UFC 2009 Undisputed
    0x54510866, // WWE All Stars
    0x57520829, // Injustice: Gods Among Us
    0x4E4D0819, // Naruto Shippuden: Ultimate Ninja Storm 2
    0x4E4D0862, // Dragon Ball Xenoverse
    0x434307FC, // Ultra Street Fighter IV
    0x454107EE, // Def Jam: Icon
    0x545408B6, // WWE 2K15
    0x54510826, // WWE SmackDown vs. Raw 2009
    0x45410915, // Fight Night Champion
    // Racing and flying
    0x45410903, // Need for Speed: Hot Pursuit
    0x4D530910, // Forza Motorsport 4
    0x545407F8, // Midnight Club: Los Angeles
    0x4D53084D, // Forza Motorsport 3
    0x425607FE, // Disney-Pixar Cars 2
    0x4D5309C9, // Forza Horizon
    0x5345084D, // Sonic Free Riders
    0x49470804, // Test Drive Unlimited 2
    0x4D530AA4, // Forza Horizon 2
    0x5451087B, // MX vs. ATV Alive
    0x41560845, // Blur
    0x45410806, // Burnout Paradise
    0x41560893, // NASCAR 2011: The Game
    0x4541094A, // Need for Speed: The Run
    0x45410876, // Need for Speed: Undercover
    0x454108B4, // Need for Speed: Shift
    0x54510829, // MX vs. ATV Reflex
    0x45410961, // Need for Speed: Most Wanted - A Criterion Game
    0x415607F1, // Transformers: The Game
    0x5553087E, // Driver: San Francisco
    0x454107D9, // Need for Speed: Most Wanted
    0x4D5307EA, // Forza Motorsport 2
    0x53450815, // Sonic & Sega All-Stars Racing with Banjo-Kazooie
    0x45410934, // Shift 2: Unleashed
    // Sports
    0x45410937, // Madden NFL 12
    0x454108E6, // Skate 3
    0x454108C6, // Madden NFL 10
    0x45410998, // FIFA Soccer 13
    0x54540894, // NBA 2K12: Game of the Year Edition
    0x454109DB, // FIFA 15
    0x4541098B, // Madden NFL 13
    0x4541094E, // NCAA Football 12
    0x45410967, // FIFA Soccer 12
    0x454108FE, // Madden NFL 11
    0x5454087A, // NBA 2K11
    0x55530850, // Motionsports: Play for Real
    0x4541087F, // Skate 2
    0x4D5308C9, // Kinect Sports
    0x54540852, // NBA 2K10
    0x454108BC, // FIFA Soccer 10
    0x454108F3, // FIFA Soccer 11
    0x545408B0, // NBA 2K14
    0x57520801, // Game Party: In Motion
    0x545408B5, // NBA 2K15
    0x415607D4, // Tony Hawk's American Wasteland
    0x4D5707E8, // Blitz: The League II
    0x4541098A, // NCAA Football 13
    0x4D5309D6, // Kinect Sports: Season Two
    // For the family
    0x41560881, // Spider-Man: Shattered Dimensions
    0x425607E5, // Disney-Pixar Toy Story 3
    0x4C4107D7, // LEGO Star Wars: The Complete Saga
    0x57520817, // LEGO Batman 2: DC Super Heroes
    0x4D5308B3, // Kinectimals
    0x454108F9, // Harry Potter and the Deathly Hallows: Part 1
    0x4C4107F3, // LEGO Star Wars III: The Clone Wars
    0x57520835, // LEGO Marvel Super Heroes
    0x575207D7, // LEGO Batman: The Videogame
    0x42560802, // LEGO Pirates of the Caribbean: The Video Game
    0x4D5308C9, // Kinect Sports
    0x53450848, // Sonic Generations
    0x57520841, // The LEGO Movie: Videogame
    0x57520845, // LEGO Batman 3: Beyond Gotham
    0x54510875, // Rio
    0x57520801, // Game Party: In Motion
    0x454108F5, // Monopoly Streets
    0x575207E6, // LEGO Harry Potter: Years 1-4
    0x4D5309D6, // Kinect Sports: Season Two
    0x55530888, // Just Dance 3
    0x4D5309C1, // Kinect Disneyland Adventures
    0x41560857, // Bakugan: Battle Brawlers
    0x415608AE, // ABC Wipeout: In the Zone
    0x4C4107DF, // LEGO Indiana Jones: The Original Adventures
    // Strategy and simulation
    0x4D5308D6, // Fable III
    0x454108E2, // The Sims 3
    0x4D530808, // Halo Wars
    0x545407E5, // Sid Meier's Civilization Revolution
    0x454108C5, // Brutal Legend
    0x45410962, // The Sims 3: Pets
    0x464507E1, // Farming Simulator 15
    0x454107DF, // The Lord of the Rings: The Battle for Middle-Earth II
    0x464507DC, // Farming Simulator
    0x434D0811, // Operation Flashpoint: Dragon Rising
    0x4541083A, // Command & Conquer 3: Kane's Wrath
    0x4B5907D6, // Tropico 3
    0x464F07D1, // IL-2 Sturmovik: Birds of Prey
    0x534307E9, // Battlestations: Pacific
    0x464F07DB, // Field & Stream: Total Outdoorsman Challenge
    0x555307F6, // R.U.S.E.
    0x4C4107D6, // Thrillville: Off the Rails
    0x415407D1, // Zoids Assault
    0x4541080E, // Command & Conquer 3: Tiberium Wars
    0x555307E0, // Tom Clancy's EndWar
    0x45410860, // Command & Conquer: Red Alert 3
    0x54540882, // XCOM: Enemy Unknown
    0x535107E3, // Supreme Commander 2
    0x4D530A95, // Zoo Tycoon
    // Music and rhythm
    0x545607D3, // Dance Central
    0x45410869, // Rock Band 2
    0x575207F0, // LEGO Rock Band
    0x55530851, // Michael Jackson: The Experience
    0x55530888, // Just Dance 3
    0x45410829, // Rock Band
    0x415607F7, // Guitar Hero III: Legends of Rock
    0x41560840, // Guitar Hero 5
    0x454108B1, // The Beatles: Rock Band
    0x45410914, // Rock Band 3
    0x4156081A, // Guitar Hero World Tour
    0x373307D2, // Dance Central 2
    0x55530873, // Rocksmith
    0x425607E9, // Hannah Montana: The Movie
    0x4B4E081E, // Dance Masters
    0x555308CD, // Just Dance 2015
    0x425607DF, // Disney High School Musical 3: Senior Year Dance!
    0x41560830, // Guitar Hero: Metallica
    0x4156085C, // Band Hero
    0x415607E7, // Guitar Hero II
    0x4B4E0820, // Def Jam: Rapstar
    0x4D4A07E7, // Zumba Fitness Rush
    0x41560883, // Guitar Hero: Warriors of Rock
    0x5553088D, // The Black Eyed Peas Experience
    // Platformers
    0x41560881, // Spider-Man: Shattered Dimensions
    0x53450848, // Sonic Generations
    0x55530836, // Cloudy with a Chance of Meatballs
    0x53450812, // Sonic Unleashed
    0x415608AB, // Skylanders: Spyro's Adventure
    0x415608AE, // ABC Wipeout: In the Zone
    0x4256081E, // Disney Infinity
    0x565507FA, // Crash: Mind over Mutant
    0x415607F2, // DreamWorks Kung Fu Panda
    0x5451085C, // DreamWorks Megamind: Ultimate Showdown
    0x41560919, // Nickelodeon SpongeBob HeroPants
    0x565507E4, // Crash of the Titans
    0x5553080C, // Prince of Persia
    0x55530884, // Rayman Origins
    0x54510824, // Disney-Pixar WALL-E
    0x4156090C, // Nickelodeon Teenage Mutant Ninja Turtles: Danger of the Ooze
    0x415607E8, // DreamWorks Shrek the Third
    0x545107F1, // Disney-Pixar Ratatouille
    0x4E4D0865, // Pac-Man and the Ghostly Adventures
    0x4156082A, // DreamWorks Monsters vs. Aliens
    0x575207D2, // Looney Tunes: Acme Arsenal
    0x54510839, // Disney-Pixar Up
    0x445007F7, // Ben 10: Ultimate Alien - Cosmic Destruction
    0x415608DA, // Skylanders: Giants
    // Puzzle and trivia
    0x415608E4, // Angry Birds Trilogy
    0x415407D7, // Catherine
    0x54510869, // You Don't Know Jack
    0x41560901, // Angry Birds Star Wars
    0x4E4D0827, // Body and Brain Connection
    0x545108AF, // Wheel of Fortune
    0x4D4A07E6, // Motion Explosion
    0x4D4A07E2, // Twister Mania
    0x545108AE, // Jeopardy!
    0x575207F5, // Scene It Bright Lights! Big Screen!
    0x54510840, // Are You Smarter Than a 5th Grader Game Time
    0x45410929, // Create
    0x4D4B07D3, // PopCap Hits! Vol. 2
    0x5A4507D1, // Battle vs. Chess
    0x504707D8, // Plants vs. Zombies
    0x4D4B07D0, // PopCap Hits!
    0x4541099F, // Zuma's Revenge!
    0x575207F8, // Scene It Ganz grosses Kino!
    0x575207F9, // Scene It Estrellas en la Pantalla Gigante
    0x4C5307DB, // Nat Geo Quiz! Wild Life
    0x494F07E8, // National Geographic: Challenge!
    0x5451089C, // Pictionary: Ultimate Edition
    0x575207FC, // Scene It Ciak! Si Gira!
};

static const StoreRow kStoreRows[STORE_ROW_COUNT] =
{
    { "Popular", 0, 24 },
    { "Top rated", 24, 24 },
    { "Shooters", 48, 24 },
    { "Action and adventure", 72, 24 },
    { "Role-playing", 96, 24 },
    { "Kinect", 120, 24 },
    { "Fighting games", 144, 24 },
    { "Racing and flying", 168, 24 },
    { "Sports", 192, 24 },
    { "For the family", 216, 24 },
    { "Strategy and simulation", 240, 24 },
    { "Music and rhythm", 264, 24 },
    { "Platformers", 288, 24 },
    { "Puzzle and trivia", 312, 23 },
};

#endif // STORE_ROWS_DATA

#endif
